---
title: "CHURCH CONCEPT"
author: "benjamini mpinga"
date: "2023-02-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### KANISA.

Neno ***Kanisa***, limekua neno kubwa na maarufu sana miongoni mwa watu. Pamoja na umaarufu na ukubwa wake pia halijaishia kuwa neno tu, bali limeenda mbali zaidi na kuwa dhana ya maisha ya kila siku, hata imefika hatua limetoka katika maana yake halisi na kupewa maana ya **Eneo maalum kwa ajili ya watu wanaoitwa wakristo wanapokutana kwa ajili ya kufanya ibada kwa Mungu wao. **Lakini haikuishia hapo tu imeenda mbele zaidi na kutafsiriwa kama **Jengo maalum, lenye sanaa mbalimbali za kufikirika, linaloonesha ishara/alama mbalimbali ikiwemo ya msalaba kuashiria hilo ndilo kanisa.**

Pamoja na tafsiri hizo mbalimbali zilizopo katika vichwa vya wanadamu wengi, pia kuna kundi ambalo ni kubwa kiasi, ambalo linajua na linaamini kwamba Kanisa linalozungumzwa katika Kitabu cha Biblia sio jengo wala eneo maalum kwa ajili ya watu kufanyia ibada. Kwa bahati mbaya maana na ukweli wanaoujua haujapata nafasi katika vichwa vya wanadamu wengi kwa kuzingatia kwamba fundisho lao halijapata nafasi ya kutosha katika maisha ya walio wengi, wenye dhana potofu ya Kanisa kuwa **Eneo au jengo.**

Katika makala hii tutachambua kidogo juu ya mambo kadhaa yanayolihusu Kanisa, kwa mujibu wa maandiko ya Biblia na vilevile tutatumia mifano kadhaa ambayo inaweza kuleta wepesi wa mtu kuelewa maana halisi iliyokuwa imekusudiwa katika kusudi la Yesu Kristo.

### Mwanzo wa jina Kanisa.

Katika Injili ya ***Mathayo 16:13 -- 20. ***Kwa mara ya kwanza tunasoma na kusikia neno Kanisa katika historia ya Biblia tukianzia kitabu cha mwanzo.

Kitabu hiki cha injili ni kitabu cha kwanza katika vitabu vyote vinavyoeleza habari za mafundisho, maagizo na matendo ya Yesu Kristo alipokuwa hapa duniani, **(Japo hakikuwa kitabu cha kwanza kuandikwa).** Hivyo Kristo mwenyewe ndiye aliyetufunulia kwa habari ya Kanisa, ambayo hakuna aliyekuwa akiijua kabla ya Ufunuo huo. tunayo kila sababu ya kumwamini yeye aliyetupa habari zote kwa maana yeye ndiye njia ya Kweli na Uzima..
 
 Hivyo katika kitabu cha kwanza kabisa katika vitabu vya injili tunakutana na neno **Kanisa,** lakini neno hili haliishii kuwa neno pekee bali Yesu Kristo analitolea ufafanuzi kwamba ni nini haswa maana ya **Kanisa.** anaanza kwa kusema, ***"wewe ndiwe Petro, na juu ya mwamba huo nitalijenga Kanisa langu, wala milango ya kuzimu haitalishinda,"*** katiika maneno haya tunapata mambo makuu matatu
  
1. Kanisa linajengwa na Yesu Kristo pekee.
1. Kanisa ni mali Yesu Kristo pekee.
1. Kanisa halitashindwa na Milango ya kuzimu.
  
### Kanisa kujengwa na Yesu Kristo.

Wakati unajiuliza maswali haya, unaweza ukaona na namna ambayo ni kwa jinsi gani isivyowezekana kanisa kuwa eneo au jengo maalumu. kama tulivyozoea kuona na kujua kwamba hayo majengo au maeneo ndiyo Makanisa. Kutokana na kauli hiyo ya Yesu, inatoa sifa moja tu kwa Kanisa, kwamba Yeye ndiye atakaelijenga, yaani ni mwendelezo ni kitu atakacho kifanya wakati ujao sio wakati ule alipokuwa akiyasema maneno hayo. Kwa maana nyepesi ni kwamba Yesu Kristo hakujenga kanisa alipokuwa na wanafunzi wake, bali ilikuwa moja ya ahadi alizozitoa kwa wanafunzi kwamba **"Atalijenga"** Kanisa lake. Hivyo ilibaki kuwa tarajio la wakati ujao.

Kwa maelezo hayo machache ni dhahiri kwamba hakuna kazi ya Mwanadamu itakayochukua utukufu wa YESU KRISTO kwa kufanya kazi za mikono na fikra  zetu, ikiwemo kujenga majengo yaliyopewa majina mbalimbali na Binadamu na kuyafanya ndiyo KANISA. Sote tunakubaliana kwamba Yesu Kristo hafanyi jambo lolote isipokuwa kwa utukufu wa MUNGU Baba na pia hafanyi kazi ya mikono ya kibinadamu bali hutenda miujiza ili watu wapate kuamini na kumpa Mungu utukufu.

***Je, kama Yesu aliahidi kulijenga Kanisa, analijenga vipi naye hafanyi kazi ya namna ya kibinadamu?.***

Ni dhahiri kwamba, Kanisa Yesu analolizungumzia ni ***Mtu***  **(Hali ya kumbadili mwanadamu kuwa Kiumbe kipya),** huo ndio ujenzi wa Kanisa la Kristo Yesu, Kwa njia ya kifo na kufufuka kwake, sisi sote tunasamehewa dhambi zetu kwa njia ya kumuamini Yeye, kisha tunapokea ahadi ya pili aliyoitoa kwa wanafunzi wake baada ya kufufuka kwake ya kwamba, anakwenda kwa Baba mbinguni ila atawaletea Roho Mtakatifu ili awe msaada, mwalimu na kiongozi hata atakaporudi kwa ajili ya kulichukua Kanisa lake.

Ahadi ya Kanisa ilikuwa ahadi ya kwanza kabla ya kufa kwake, na Ahadi ya Roho Mtakatifu ni ahadi ya kwanza baada ya kufufuka kwake, Ahadi hizi zote watu hupenda kuzitofautisha na haswa wanazitofautisha kwa moja kuwa Jengo la kibinadamu na nyingine kubaki kuwa uweza wa ndani ya Mtu. 

Kimsingi mwanadamu anapopata Neema ya Yesu Kristo ya kusikia Neno lake na kumuamini anapata mambo makuu mawili kwa hatua tofauti.

1. **Anasamehewa dhambi kwa njia ya Toba, (Kupitia kifo chake)**
  
1. **Anapata karama ya kuzaliwa mara ya pili kwa kujazwa Roho Mtakatifu. (Kupitia kufufuka kwake)**
  
Toba sio maungamo ya dhambi kwa kanuni za sala tunazozijua, bali ni majuto ya ndani ya moyo na kiu ya kutokutaka kurudia kufanya makosa na kuziacha njia za kwanza za dhambi.

Hivyo kupitia ahadi ya kwanza ya Yesu Kristo baada ya kufufuka ya kutuletea Roho Mtakatifu, ndipo ahadi ya kwanza ya Yesu Kristo kabla ya kifo chake, ahadi ya kulijenga kanisa lake inapoanza kutimia. Hivyo kanisa la Kristo ni mwanadamu anapopewa uweza wa kimungu wa kuishinda dhambi ambayo kwayo ilitupasa kwenda mautini, Lakini sasa tunaishinda mauti kwa Neema ya ukombozi, ndilo Kanisa litakalokuja kunyakuliwa siku ya ufufuo wa pili.

Hivyo kuyafanya majengo yetu tuliyonayo kuchukua utukufu wa Kanisa ni kushusha utukufu wa Yesu Kristo na kumpa mwanadamu, maana kunamfanya mwanadamu kuwa na dhaifu kuliko majengo ya dunia hii. ndio maana hata katika nyakati hizi unaweza kushuhudia mambo yanayoleta kufuru kwa Mungu. kwa  watu kugeuza Huduma yenye utukufu wa Mungu kuwa biashara, kwa kuyageuza majengo ya dunia hii kuwa KANISA na kuyageuza kuwa taasisi, mashirika na mali za watu binafsi. Hii yote ni kwasababu ya kupotea kwa maana halisi ya **KANISA aliloliahidi Yesu Kristo**.

Rejea: ***Matendo ya Mitume 14:27, Matendo ya Mitume 16:5, Matendo ya Mitume 2:47, Matendo ya Mitume 8:1 -- 3, Matendo ya Mitume 9:31, 1Wakorintho 14:23, Wakolosai 4:15.***

Tumeona kwamba kanisa ni Mwanadamu aliyeiamini Injili (Yesu Kristo) kisha akasamehewa dhambi kwa njia ya Toba, (kwa Neema ya upatanisho wa Yesu Kristo kwa kupitia kifo chake), kisha akazaliwa mara ya pili kwa njia ya Roho Mtakatifu kupitia kufufuka kwake.

### KANISA MWILI MMOJA WA YESU KRISTO.

**Imani + Toba + Roho Mtakatifu = KANISA (Mwili wa Yesu Kristo).**

### Umoja wa Roho.

Baada ya Mtu kuzaliwa kwa Roho wa Kristo Yesu, anaunganiswa kuwa Roho moja na Yesu  na Yesu Krsto ni roho moja na Mungu Baba (Jehova), na Roho Mtakatifu ni pamoja na Baba na Mwana, hivyo tunapozaliwa Rohoni tunakuwa Roho moja na Mungu Baba, Yesu Kristo kupitia Roho Mtakatifu. Katika umoja huu hakuna tena wawili bali Mmoja tu yaani Mungu. Hivyo tunapokusanyika pamoja wale tuliyo okolewa, tunahesabiwa kuwa mmoja mbele za Mungu na sio katika wingi tena kwa maana Roho zetu zimekuwa Moja katika Kristo Yesu.

Hivyo mfano wa mwili ulivyo mmoja, ndivyo nasi tunakuwa wamoja, yaani **Yesu Kristo ambaye ni Kichwa na Kanisa ni Mwili.** hivi ndivyo unaweza kuona jinsi gani ilivyo vigumu kumtenga Kristo Yesu na Kanisa, au Kanisa kujitenga na Kristo Yesu kwa maana kwa pamoja wanautengeneza mwili mmoja. **Je, Kichwa kinaweza kuishi bila Mkono au bila Mguu ama bila Macho ama bila Kinywa?** jibu ni kweli kwamba mwili unaweza kuishi bila viungo hivyo. Ila mwili hauwezi kuishi bila Kichwa. Ndivyo kanisa lilivyo tegemezi kwa Kristo Yesu, yaani haliwezi kuwepo bila YESU KRISTO. Maana litakuwa limekufa. Mwili unaweza kupata ulemavu wowote ila kichwa kikawa salama na mwanadamu akaendelea kuishi, lakini kichwa kikifa basi mwili hauwezi kuishi tena, ndivyo nguvu ya Yesu Kristo ilivyo kwa Kanisa.

Hivyo kama Mtu asivyoweza kuuendesha mwili wake pasipo Kichwa basi ndivyo Kanisa lisivyoweza kujiendesha pasipo Yesu Kristo, Kwa maana sahihi Mtu hawezi kujiokoa mwenyewe isipokuwa ameokolewa, na anaokolewa kwa Neema. kwa maana anayeokoa ni mmoja tu **Yesu Kristo** ambapo kwa kuokoa kwake ndivyo anavyolijenga Kanisa lake. Kanisa linaendelea kumtegea yeye siku zote kama mwili unavyotegemea kichwa.

Yeye asemaye **"nimeokoka"** na ajipime fikra na kauli yake, kwa sababu ni makufuru mbele ya Mungu. Tujumbuke shetani hupitia mambo madogo madogo kutufarakanisha na Mungu.  Hivyo inatupasa kuwa waangalifu wa mambo madogo madogo, yasije yakatuangusha na kututengenezea wigo wa kumuona Mungu katika maisha yetu.**SISI HATUOKOKI BALI TUNAOKOLEWA KWA NEEMA**.

Rejea ***Efeso 2: 1 -- 10, Warumi11: 1 -- 6, Warumi 3: 24, Tito 3: 3 -- 10, Efeso 2: 1 -- 10, Warumi11: 1 -- 6, Warumi 3: 24, Tito 3: 3 -- 10***


1. **HATUOKOKI BALI TUNAOKOLEWA KWA NEEMA**
1. ***HATUJENGI KANISA BALI YESU NDIYE HULIJENGA KANISA**
1. **HATUPASWI KUTUBISHWA BALI TUNAPASWA KUTUBU MAKOSA YETU KWA MUNGU**
1. **HATUFUNDISHWI IMANI BALI TUNAKIRIMIWA KIPAWA CHA IMANI NA MUNGU** ***(Luka 22)***
1. **KANISA SIO JENGO BALI NI MWILI WA KRISTO.**
  
### MAKUTANO YA KANISA.

Imeandikwa kwamba, ***"Msiache kukusanyika kama ilivyo desturi ya Makanisa yote ya watakatifu."*** Kupitia andiko hili tunaona kwamba jambo jema kukusanyika kwa ajili ya kuhudumiana kwa vipawa vya Roho Mtakatifu, lakini pia tunalazimika kukutana kwa taratibu njema na zinazompa Mungu utukufu. Kwa maana ni desturi njema na yenye kibali machoni pa Mungu. Hivyo basi tunapokutanika tafsiri yake ni kwamba kanisa kuungana na kuwa ushirika wa Roho wa Mungu. nguvu ya kila mmoja wetu katika ushirika wa Roho kusudi Kristo apate kuujenga mwili wake katika uweza na utukufu wa Mungu Baba..

Rejea:***Waefeso 5:27, 1timotheo 3:15, efeso 5:17, Wakolosai 1:18.***

### Taratibu wakati wa Makutano.

Zipo taratibu nyingi zinazoendelea kuchagizwa katika makutano mbalimbali, taratibu ambazo ukizitazama, kuzitafakari na  kuzitafsiri kwa mujibu wa maandiko, zipo kinyume kabisa na maagizo ya Yesu Kristo. Katika sehemu hii tutaangazia maeneo machache yanayoweza kuwa kama mfano wa upotofu au usahihi wa taratibu hizo.

1. TARATIBU ZA UENDESHAJI WA IBADA. **Sala, Mikesha, Meza ya bwana na Madhabahu.**

1. TARATIBU ZA MATOLEO KATIKA IBADA. **Sadaka, Shukrani na Fungu la kumi.**

1. TARATIBU ZA WOKOVU KWA MATENDO YA MWILI, (SALA YA TOBA NA UBATIZO WA MAJI)
**Kuongoza sala ya toba kwa waamini wapya, kufundisha kunena kwa lugha na kubatiza kwa maji**

1. TARATIBU ZA MAFUNDISHO YA MAANDIKO (BIBLIA).
**Kufundisha Imani, Mafundisho ya ndoa, Kufuata Biblia kama mbadala wa Roho Mtakatifu na Kuamini wasifu wa Watu badala ya Karama za Roho Mtakatifu.**

## Tararibu za uendeshaji wa ibada.

**Maombi, Mikesha, Meza ya bwana na Madhabahu.**

Katika kipengele hiki tutaangazia namna makusanyiko ya leo yanavyoenda kinyume na maelekezo ya waasisi wetu katika imani kwa Kristo Yesu.

### SALA.**

Katika sala za wengi kwenye makutano, ni maombi yeny kumwelezea Mungu mambo yanayomuhusu mwanadamu, tofauti kabisa na maagizo yanayotutaka tuutafute kwanza ufalme wa Mungu, kisha mengine tutazidishiwa, pia imeandikwa katika maandiko kwamba Tumuombe Mngu kwa jina la Yesu Kristo, naye atatutendea kwa kadiri ya mahitaji yetu.

*Je,nitamuombaje Mungu kwa usahihi?*. swali hilo hautakuwa wa kwanza kujiuliza, kwa maana hata wakati Yesu akiwa na wanafunzi wake walimuuliza wakisema "Mwalimu, Tufundishe kusali". Yesu akawajibu akawaambia Msalipo salini hivi.

**Mathayo 6:9 -- 21**.Jina maarufu inaitwa {SALA YA BWANA}, sala hii ukiisoma na kuitafakari, basi huna budi kuona mwisho/matokeo ya sala yako kabla ya kuanza kuomba.

***"Baba yetu,Uliye mbinguni, Jina lako litukuzwe, Ufalme wako uje, Mapenzi yako yatimizwe hapa duniani kama mbinguni, Utupe  riziki yetu ya kila siku, Utusamehe makosa yetu kama nasi tunavyowasamehe watukoseao, Usitutie majaribuni bali utuokoe maovuni, kwa kuwa ufalme, nguvu na mamlaka ni vyako amen.***

**"Baba yetu,Uliye mbinguni,Jina lako litukuzwe."** maana yake ni kwamba, jambo la kwanza katika lolote utakaloliomba ni lazima liwe jambo linaloonesha utukufu wa Mungu, wala sio utukufu/hadhi/heshima zetu wenyewe, au Mamlaka yeyote ya kibinadamu.

**"Ufalme wako uje."** jambo la pili katika maombi yetu, ni lazima kile tunachokiomba kiwe kinaruhusu mamlaka ya Mungu, katika jambo hilo tunaloliomba.

**"Mapenzi yako yatimizwe hapa duniani kama mbinguni."** maana yake ni kwamba, hitaji lolote tulilonalo, lisiwe kikwazo cha matakwa ya Mungu juu ya maisha yetu hapa duniani. yaani hitaji lako lisije kujenga uadui na hitaji la MUNGU. kama vile malaika mbinguni wanavyoyatenda mapenzi ya Mungu, basi nasi imetupasa kuyaweka kwanza mapenzi ya Mungu mbele kisha yetu baadae.

**"Utupe  riziki yetu ya kila siku."** sehemu hii kuna tafsiri mbili muhimu kuzifahamu, ya kwanza ni kwamba kipengele hiki katika sala kinagusa habari ya riziki kama mapato ya utafutaji wa hapa duni, ni vyema na tunapaswa kumuomba Mungu katika utafutaji wetu wa mahitaji ya mwili. ili kwamba tunapojaaliwa kupata basi tujue kwamba ni kwa baraka ya Mungu na sio uwezo wako binafsi.

Lakini tafsiri kubwa zaidi na yenye uhalisia katika mawazo ya Mungu na katika Roho ni hii........

Mbali na kwamba Mungu anatubariki kwa mahitaji ya mwili kwa chakula cha kawaida, Kwasababu tumeomba  **ufalme wako uje**, hivyo haiwezekani ufalme wa Mungu uje alafu usiwe na vitu vyake, yaani vitu vyenye utukufu wa kimungu. chakula cha ufalme huo ni moja ya vitu vitakavyokuja na kujidhihirisha maishani mwetu. hivyo chakula chetu cha kawaida cha kidunia hakiwezi kutumika  katika ufalme wa Mungu, kwasababu ni chenye kuharibika. Ila kipo chakula kisichohubiriwa kabisa cha ufalme huo usioharibika, na chakula hicho tunakijua kupitia kitabu cha **Yohana 4:34** na andiko linasema **“chakula changu ndicho hiki, niyatende mapenzi ya baba yangu na nikaimalize kazi”**.

Zaidi ni kwamba tutambue kwamba hatuwezi kufananisha ufalme wa Mungu na mambo ya duniani, hivyo yote yaliyozungumziwa katika sala hiyo ni mambo yenye utukufu wa Mungu. na zaidia ya yote Biblia inaandika **UFALME WA MUNGU SI KATIKA KULA WALA KUNYWA** Hivyo chakula kilichoozungumziwa hapo ni kile tulichokiona katika kitabu cha Yohana.

**"Utusamehe makosa yetu kama nasi tunavyowasamehe watukoseao."** hii inamaana imetupasa tunapokuwa tunaomba basi tusiwe na neno na mtu yeyote bali tuwe wasafi wa mioyo na fikra zetu, tusiwe na **mawaa, wala visasi, wala hila, wala ghadhabu, wala manung'uniko**. kwasababu imeandikwa **kama umeleta sadaka kwa Bwana nawe ukakumbuka kuwa una neno na ndugu yako basi, iweke pembeni nenda kapatane naye kwanza ndipo uje uitoe hiyo sadaka,** na katika maombi pia imetupasa kumuendea Bwana Mungu tukiwa wasafi wa mioyo.

**"Usitutie majaribuni bali utuokoe maovuni."** katika kipengele hiki tunaona maombi yetu yanapaswa kuomba msaada wa Mungu pindi ifikapo siku na saa ya kujiliwa kwa ajili ya majaribu. ili Bwana Mungu atusaidie ili tuweze kushinda hila za yule muovu. hapa ndugu zangu lazima tujue kwamba ipo siku na saa ya kujiliwa kwa ajili ya kujaribiwa hivyo yatupasa kuwa tayari kwa ajili ya siku na saa hiyo maana hatuijui. hivyo yatupasa tuzivae silaha zote za Mungu.

**"kwa kuwa ufalme, nguvu na mamlaka ni vyako amen."** Na mwisho lazima maombi yetu yaoneshe kutambua mamlaka na uweza wa Mungu katika maisha yetu, na kwamba hatutendei tunavyotaka sisi bali anavyotaka yeye mwenyewe. 

**Ndugu zangu katika mtiririko huo wa sala ya Bwana Yesu aliyotuachia liko wapi jambo hata moja la hisia na fikra za mwanadamu?**

hivyo nimalize kwa kusema  msingi wa maombi yetu umekuwa kikwazo mbele ya Mungu, kwa maana maombi yetu yamejaa matakwa yetu na matarajio yetu wala siyo matakwa ya Mungu. kinyume kabisa na taratibu, hivyo nikumbushe tena kwamba, tutajikuta tukikufuru Mungu, huhu tukiwa tunadhani kwamba tunamuomba. maombi hayo katika mtiririko hapo juu yanaweza kutumika kama muongozo wa maombi yetu yeyote tuliyonayo kwa Mungu.

Hivyo maombi yetu yeyote tuliyonayo yamepaswa kuakisi katika mtindo ambao unaonesha mamlaka ya Mungu na matakwa yake, naye atatusikia na kutujibu kwa wakati wake.

### MEZA YA BWANA.

***Luka 22:14 -- 20.*** Katika mstari tunaona chanzo haswa kinachotumiwa au kuonesha kwamba ni halali kwa matutano kula mkate na divai kama (meza ya bwana), lakini ukisoma kwa makini utagundua jambo muhimu sana, kwamba chakula kile kilikuwa cha mwili na kilikuwa ni desturi ya Wayahudi kushiriki aina hiyo ya chakula.  Lakini Yesu mwenyewe anasema "Sitakula tena mzao wa Mzabibu hata nitakapokula ule mpya utakapokuja ufalme wa Baba yangu" Mungu wetu.

- **je, kama Yesu hakutumia chakula cha mwilini kututakasa kabla ya kufa, kwa nini sisi tuendelee kutumia chakula kile cha mfano kana kwamba ni vitu vyenye uwezo wa kutubadili maisha yetu ya dhambi kuwa ya utakatifu?**

- **Je,inawezekanaje vitu vya mwilini vitusafishe Roho zetu?**

- **je, Yesu anaposema chakula ni kwa tumbo na tumbo ni kwa chakula, leo tunawezaje kula mwilini tukatakaswa Rohoni?**

- **Kama ni kweli mkate na divai ile ya mfano vilikuwa na uwezo wa kumpa mtu utakatifu, kwa nini Yesu alikufa kifo halisi ili atuokoe?**

- **Yesu mwenyewe anasema ufalme wa Mungu si katika kula wala kunywa, je tunapokula mkate na kunywa divai ni kwa ajili ya utukufu wa nani?**

- **Kama Yesu Kristo alijitoa sadaka kwa ajili ya wenye dhambi, je ni kwanini Makanisani tunaambiwa ili tushiriki meza ya Bwana sharti tuwe tumeungama dhambi, ndipo tushiriki?, Kwani Damu na Mwili wa Yesu msalabani ulitolewa kwa ajili ya wenye dhambi au watakatifu.?** kama ni kwa ajili ya wenye dhambi mbona makanisani wanashiriki walio safi, wakati Yesu aliwataka wenye dhambi?**

Kwa maswali hayo machache unaweza kuona kwamba kuna mtego Mkubwa na wenye hila ya muovu Ibilisi, na ameupenyeza katikati ya watu kwenye makutano na kuleta ibada za sanamu makanisani. Kwa kusudi la kuwafanya watu waelendelee kumwabudu yeye pasipo wao kujua, kwa maana Ibilisi anajua kati ya jambo kubwa linalompa Mungu utukufu ni Ibada ya kweli. Hivyo ameleta Mitego ambayo wengi hatujaigundua na imetunasa tumeanza kumwabudu shetani katika makusanyiko mengi ulimwenguni kote. Tukitaka kukielewa chakula cha Bwana basi imetupasa tule katika meza yake na kwenye Ufalme wake kama anavyoahidi wanafunzi wake katika. ***Luka 22 :28 -- 30.*** 

Meza ya bwana inayotolewa katika Makutano ya Mkate na Divai ni batili. Ufalme wake tunajua ni ufalme wa Roho. Hivyo hatuna budi kula chakula cha Roho katika Meza ya bwana. Daudi anasema kwenye  zaburi ya 23 ***"Waandaa menza mbele yangu,machoni pa watesi wangu."*** Tunaona kwamba Meza ya bwana mara zote anaandaliwa machoni pa watesi, kama Yesu alivyoshiriki meza yake mbele ya watesi wake (yaani hao waliomtesa na kumsulubisha). Kadhalika nasi pia imetupasa kushiriki mateso yake kwa ajili ya Utukufu wa Mungu. 

Na katika kitabu cha **Yohana 4:34** kinasema **“chakula changu ndicho hiki niyatende mapenzi ya baba yangu na nikaimalize kazi.”** Vivyo hivyo nasi imetupasa kudumu katika Kristo Yesu hadi pale atakapomaliza kazi yake ya Ukombozi katika miili yetu. mwisho tusome ***Waefeso 5:5 --17***

- MEZA YA YESU HAPA DUNIANI NI KUKUBALI KUPITIA MATESO INAPOBIDI (KWA MAPENZI YAKE)KWA AJILI YA UTUKUFU WA MUNGU
- CHAKULA CHA BWANA YESU HAPA DUNIANI NI KUYATENDA MAPENZI YA MUNGU NA KUFUATA WITO ALIOKUITIA UKAMTUMIKIE

1. **je. ni kweli meza tunayoshiki katika makusanyiko inaandaliwa mbele ya watesi?** au 

1. **je, maisha ya utakatifu yanaonekana katika makusanyiko au kwa watu wasiojua kuhusu upendo na neema ya Yesu Kristo?. Ambao hao ndio watesi wa watakatifu.**
### MIKESHA YA MAKANISANI.**

### IBADA ZA MIKESHA MAKUSANYIKONI.

Kwa kawaida mikesha mingi katika makutano sio jambo geni japo swali kubwa la msingi linaweza kuwa...

**je, mikesha hiyo ni kwa ajili ya kutiza andiko au kwa ajili ya maongozi ya Roho Mtakatifu ameamuru ifanyike?.** Kama ni kwa maongozi ya Roho basi hakuna mjadala wa kuyakosoa, ila kama ni kwa sababu imeandikwa ***"kesheni mkiomba kwa maana hamjui wakati wala saa atakayokuja mwana wa Adam."*** Basi tatizo ni kubwa sana, kwa maana hata ratiba zetu za mikesha zinaonesha jinsi gani tulivyolitafsiri neno hilo kimakosa. **kwanini tuwe na siku maalum ya kukesha kama hatujui saa?,** **kwanini tusikeshe kila siku.?**

Tafsiri sahihi ni kwamba, imetupaswa kuwa tayari wakati wote kwa maana imetupasa kumcha Mungu kila saa kila wakati, na sio kwa kipindi ama siku au masaa maalumu, kwani wakati ule tunaodhania kwamba wakati bado basi anaweza kuja na akatukuta hatuko tayari, hivyo muda na saa na wakati wote ni wa Mungu, hakuna muda maalum kwa ajili ya Mungu na muda kwa ajili ya mambo yako. kama ni kazini basi ufanye kwa kumtukuza Mungu, kama ni nyumbani vivyo hivyo na kama ni katika maradhi basi hatuna budi kumtukuza Mungu hata ijapo mauti ya kifo cha mwili bado imetupasa kumtukuza MUNGU.

### MADHABAHU**

Katika majengo ya makanisa niliyoyazungumzia hapo awali, ni kawaida kukuta mahala fulani mbele ya jengo hilo, pameandaliwa na pamewekwa tofauti kabisa na eneo lingine ambapo makutano wanakaa. Hiyo ni kutokana na umuhimu wa eneo hilo katika tafsiri yetu ya kibinadamu, eneo hilo hupambwa kwa vitambaa na rangi mbalimbali, nyingine zikiwa zinabeba maana fulani na nyingine ikiwa ni kuleta muonekano mzuri wenye kupendeza machoni. Sio ajabu kwa nyakati hizi unaweza ukaona jengo ambalo halijakwisha vizuri ujenzi ila ukiingia ndani ya jengo hilo liitwalo Kanisa, ukakuta pamepambwa tofauti na uhalisia wa jengo.

Ukweli ni kwamba ni eneo linaloheshimika zaidi katika jengo lote la kanisa, wengine wakipita mbele yake huina na kutoa ishara ya heshima,na wengine husujudu kama kuashiria utakatifu wa eneo hilo,na wengine hawawezi hata kuthubutu kupakanyaga kwa miguu yao wenyewe kwa hofu ya utakatifu wa eneo hilo.

Kwanza tutafute Neno madhabahu limeanzia wapi na ilikuwa kwa ajili ya nini,na lilibeba maana gani nyuma yake.***Mwanzo 8: 20, Mwanzo 12:7.***Tunaona madhabahu ilikuwa ni eneo la kumtolea Bwana Mungu sadaka ya Kuteketeza,ikiwa ni wanyama au mazao,na vilikuwa vinateketezwa vingali hai.hivyo ndivyo madhabahu ilivyokua inajengwa na kufanya kazi ya kumtolea Bwana Mungu sadaka za kuteketezwa.

1. **Je,ni kweli panaweza pakatokea katika dunia kukawa na eneo ambalo ni tukufu Kuliko Mungu?**
1. **Je,kama Mungu anaishi ndani kwa njia ya Yesu Kristo ni kweli kwamba eneo fulani katika nyumba ya makutano inaweza ikawa na heshima kuliko mtu mwenye Mungu ndani?**
1. **Je,Kati ya mwanadamu na vitu vyote katika dunia ni kipi kikuu zaidi?**
1. **je,ni sahihi kutoa utukufu kwa mcha Mungu na kutukuza Eneo linaloitwa madhabahu?**
1. **Je, Mungu hukaa ndani ya watu au hukaa katika jengo?**
1. **Kwanini tunatukuza maeneo dhaifu na manyonge ya dunia hii kwa utukufu ambao hatuwapatii watu ambao Kristo Yesu anakaa ndani yao?**

### Taratibu za Matoleo katika ibada

**SADAKA,SHUKRANI NA FUNGU LA KUMI**

### SADAKA**

Sadaka ya kweli na yenye kibali mbele ya Munu ilikuwa moja tu nayo ni **Yesu Kristo kufa msalabani kwa ajili ya dhambi za wanadamu.** ili yeyote atakayemuamini kwamba alikufa kwa ajili ya dhambi zake na kutubu basi apate msamaha ambao ni upatanisho kati ya mwanadamu na Mungu baba (Jehova). Hiyo ndiyo sadaka ya kweli na kwa hiyo pekee tunapata kibali cha kufutiwa makosa. Sadaka hiyo nasi pia tunaishiriki kwa kuyatoa maisha yetu, yawe chini ya Imani kwa Yesu Kristo kupitia Roho Mtakatifu. tumepewa neema ya ukombozi ili tuyaishi maisha yampendezayo Mungu kwa uweza wa Yesu Kristo. sio kwa matendo bali kujitoa maisha yetu kuwa sadaka kwa Mungu, na sio vitu vyetu, kwa maana Yesu hakufa kwa ajili ya mali zetu bali kwa ajili yetu sisi, hivyo sadaka yenye kibali kwake ni **MIMI NA WEWE NA SIO VITU VYAKO (MALI)**.

Je kwa kusema hivyo ni kwamba matoleo ya mali zetu hayana maana yeyote?

Lah! hasha matoleo hayabatiliki endapo tunatoa kwa moyo safi na bila majivuno wala kujitukuza. Hatutoi sadaka katika vitu tulivyonavyo bali sadaka ni sisi wenyewe, ila mali zetu ni matoleo kwa ajili ya kutenda kazi zimpendezazo Mungu. (***Kusaidia wahitaji, Kusaidia wagonjwa kwa matibabu, Kulisha Yatima na wajane wasiokuwa na msaada na mambo yenye kufanana na hayo.***)

### SHUKRANI**

Shukrani ni moja ya matoleo yanayochangwanywa na uhalisia wake kwa mujibu wa fundisho la Mungu. Elimu iliyoenea juu ya shukrani ni kwamba unapaswa kumshukuru Mungu kwa kile anachokupatia katika malengo yako au kazi ya mikono yako. Ni kweli Mungu huzibariki kazi zetu tuzifanyazo kwa halali na pasipo dhuluma, lakini imetupasa kushukuru kwa kila jambo, sio kwa ajili ya kile tulichijiwekea malengo na kikafanikiwa au kutimia. Ila pia kushukuru kwa ajili ya jambo maalumu ni kumpunguzia Mungu utukufu, kwa maana Hata Afya na Uhai ulionao wakati ukiwa nacho na wakati huna bado ni jambo likupasalo kushukuru. Tusimshukuru Mungu kwa mambo maalumu bali tunapaswa kumshukuru kwa kila jambo, kila saa na kila mahali kwa maana kuona siku na saa unayoiona ikiwa kuna changamoto au faraja bado ni Neema yake Mungu. Tukiendelea kumshukuru Mungu kwa kuangalia alichotubariki kwa mwili, basi tutapoteza shabaha ya utukufu wa Mungu katika Roho. (**Matendo mema na maisha ya kumtegemea Yesu Kristo, ndiyo shukrani yenye kibali machoni kwa Mungu, kwa kutambua upendo wake hata akatusamehe dhambi zetu kwa njia ya kifo cha Yesu Kristo.**) ***Warumi 12:1***

### FUNGU LA KUMI**

Fungu la kumi ni aina mojawapo ya sadaka yenye maswali mengi miongoni mwa waamini, Asili ya fungu la kumi na namna lilivyokuwa inatolewa na namna ya kutumika katika agano la kale, ni kwamba, Bwana Mungu aliwaamuru wana wa Israeli Kutoa sehemu ya kumi ya vitu vyao (wanyama, mazao) kwasababu walikuwa wafugaji na wakulima. Aliwapa utaratibu wa kutoa na matumizi yake. kama ilivyokuwa kwa sadaka zingine katika agano la kale, zilivyowekewa utaratibu wa kutumika.

***Mwanzo 14:20.*** Katika kitabu hiki, ndipo tunaona kwa mara ya kwanza neno FUNGU LA KUMI, na aliyelitoa ni Abrahimu akimpa Mfalme wa selemu Melkizedeki sehemu ya kumi ya vitu vyote alivyoviteka kutoka katika sehemu za hao adui zake aliowashinda katika vita. Katika sehemu hii hakuna sehemu yeyote iliyoandikwa kwamba Mungu alimwagiza Abrahamu ampe Melkizedeki sehemu hiyo ya kumi, bali baada ya Melkizedeki kutoka kwenda kumlaki Abrahamu baada ya kushinda vita. Melkizedeki alikuwa kuhani wa Mungu aliye juu sana, Ndipo Abrahamu aliamua kumpa sehemu ya kumi ya mali alizozitwaa kwa maadui zake.

(Kufuatia hayo nashawishika kusema kwamba Abrahamu alikuwa mcha Mungu na alikuwa mnyofu mbele ya Mungu, hivyo yawezekana alipata muongozo wa Mungu kabla ya kulifanya jambo hilo.Au kwakuwa Mungu alikuwa kiongozi wake basi Alimpa hekima ya kufanya jambo jema lenye kumpendeza Mungu.) hayo ni mawazo yangu sio maandiko yasemavyo.

Lakini ukitaka kuamini kwamba kulikuwa na busara ya Mungu katika moyo wa Abrahamu, ukisoma agizo la kutoa fungu la kumi, halikuishia kwa Abrahamu, bali linakuja kutolewa kama Amri kwa wana wa Israeli baada ya kutoka Mirsri.

***Kumbukumbu la Torati 14:22 -- 29.*** Katika kitabu hiki tunaona namna ambavyo fungu la kumi liliagizwa kutolewa ikisema, **"Utatoa sehemu ya kumi ya maongeo yako na wanyama na divai na mafuta, mwaka kwa mwaka."** Lakini inaenda mbele zaidi na kuonesha namna unavyopaswa kutolewa na jinsi ya kutumika kwake.

### TARATIBU ZA IBADA ZA KIYAHUDI**.

**baada ya kupata msingi wa kuanzia mjadala wetu, swali linaloanza ni Je, Mkristo kutoa Fungu la kumi ni agizo la nani?, Mapokeo, Yesu Kristo, Mitume au Wakuu wa dini?.**

Wayahudi walishika na kuyafuata yote waliyoamuriwa kwenye torati, walitoa kwa mujibu wa taratibu za torati ili wampendeze Mungu aliyewapa torati kwa mkono wa Musa. Lakini pamoja na kwamba walitoa ila walizitumia zaka hizo kwa mujibu wa maelekezo ya Torati hiyo hiyo.

Torati iliagiza kwamba, ukishakuvitoa hivyo vitu vya fungu la kumi, utakula wewe uliyevitoa na familia yako na mlawi aliyeko katika nyumba yako kwa maana mlawi hakupewa sehemu katika Israeli bali alikuwa ni kuhani wa Mungu. Taratibu hii iliendelea hata wakati Yesu alipokuja alikuta utaratibu huo unadumishwa na mambo mengine yaliongezeka, kwa mujibu wa maandiko katika kitabu cha Yohana, siku moja  Yesu alikwenda hekaluni akakuta watu wamegeuza sehemu ya hekalu kuwa soko. akapindua meza na kuwafungulia mifugo na njiwa akisema **"Nyumba ya Baba yangu iliwekwa kuwa nyumba ya ibada, ninyi mmeigeuza kuwa soko".** Hayo yalikuwa mwisho wa mwaka kwa Israeli na walikuwa wakikutana Yerusalemu kwa ajili ya kumwadhimisha Bwana Mungu na kutoa zaka na sadaka za maondoleo ya dhambi pamoja na sadaka nyingine.

Utaratibu ulitaka pia baada ya mwaka wa tatu, mtoaji wa fungu la kumi aitende sadaka hiyo na kuiweka ndani mwake, yaani hatapeleka mahala pa makutano bali atakula yeye na watu wa nyumbani mwake na mgeni na mjane na yatima na mlawi kwa maana hakupewa sehemu katika Israeli. Na maandiko yanasema imempasa mtoaji wa fungu la kumi kufanya hivyo ili kusudi ajifunze kumcha Bwana Mungu na ndipo Mungu ataibariki kazi ya mikono yako.

**Hivyo watumiaji wa sadaka ya Fungu la kumi ilikuwa ya makundi yafuatayo.**

1. Mtoaji wa sadaka ya Fungu la Kumi.
1. Familia yake
1. Mgeni wa nyumbani kwake
1. Mjane
1. Yatima
1. Mlawi

**Je, Mlawi alikuwa nani? na kwa nyakati za sasa anafananishwa na nani?**

Mlawi alitokana na kabila la Lawi, moja kati ya watoto wa Yakobo (Israeli), watu wa kabila la lawi hawakupewa sehemu ya kumiliki katika Israeli (Ardhi) bali wao Mungu aliwateuwa kuwa makuhani katika hekalu la Mungu. tukianza na MUsa na Haruni hawa wote walikuwa watu wa kabila ya Lawi. Na kuhani wa kwanza alikuwa Haruni Ndugu yake Musa. Ilikuwa ni sharti kwamba katika miji yote ya Israeli mlawi akitaka hifaghi ni sharti apewe kwa maana hakupewa fungu la ardhi ya kumiliki katika nchi ya ahadi, na pia waliishi katika Mahekalu, makabila mengine walikuwa wakiwachukua majumbani mwao kwa ajili ya kuwafanya makuhani katika kutoa sadaka zao kwa Mungu na kuendesha ibada kwa taratibu zao.

Hivyo Torati ilisema utakapotoa fungu lako la kumi, usimsahau na Mlawi maana yeye haya sehemu ya kulima, kufuga, wala kufanya shughuli za uzalishaji kama wengine. Hivyo umkumbuke katika hivyo Mungu alivyokubariki navyo. Kama yupo katika familia yako basi utashiriki naye katika kuvitumia vitu hivyo kadiri moyo wako utakavyopenda.

Katika zama hizi najaribu kumfananisha Mlawi sawa na Mchungaji wa Dhehebu. Ninatumia lugha "najaribu" kwa sababu katika Agano jipya Hakuna mfanano wa taratibu za ibada kama Agano la kale, Hivyo pia kumfanyanisha mchungaji na mlawi ni kana kwamba ni kuweka kiraka cha zamani katika vazi jipya. Jambo ambalo sio tu la kukemewa bali kuachwa mara moja. Ninasema haya kwa sababu Uchungaji ni karama ya Mungu anayompa Mtu aliyekwisha kumuokoa kwa njia ya Imani, kwa ajili ya kutunza Roho za wateule wa Mungu waliokombolewa kwa Damu ya Yesu Kristo katika nyakati za mapito ya kibinadamu. 

### TARATIBU ZA MAKUTANI YA AGANO JIPYA.

***Je, ni halali kwa Mkristo kutoa fungu la kumi? kama ndio kwa mujibu wa nini? ma kama lah! hapaswi ni kwa mujibu wa fundisho gani?.***

Tukisema ni halali tutakuwa tunajidanganya wenyewe, kwa sababu maandiko yatatupinga na kwamba tutakwenda kinyume na kusanyiko la kwanza la Mitume waliokuwa Mashuhuda wa ile Nuru. Ambao ndiyo waasisi wa Imani katika Kristo Yesu. Kwani kwa andiko moja tu inatosha kubatilisha yote yaliyokuwa katika agano lile la kwanza (Agano la kale).

Rejea......***Waebrania 7: 1 -- 28, Waebrania 8: 1 -- 13.** 

1. **kama agano lile lilikuwa imara kwanini tupewe agano jipya?**

1. **Kama agano lile lilibatilishwa, basi na ukuhani wake umebatilishwa, kwa maana sasa tunaye kuhani mmoja tu, ndiyr Yesu Kristo.**

1. **Kama sheria haikuweza kumkomboa Mwanadamu, bali Neema ya Kristo Yesu, hivyo hatuwekwi tena chini ya sheria.**

Kwa kumalizia swali letu ni vyema pia tukaangalia ni kwa namna gani hao Mitume wa kwanza katika Imani yetu kwa Yesu Kristo, walivyofanya taratibu katika matoleo (Sadaka) kwenye makutano/walipokusanyika?, **je. Fungu la kumi lilikuwepo katika matoleo yao na kama halikuwepo nini kilisababisha lisiwepo?.**

***Matendo ya Mitume 4: 31 -- 37 na Matendo ya Mitume 5: 1 -- 14.*** Katika mistari hiyo tunaona kwamba hao waamini wa kwanza wa Imani kwa Yesu Kristo, walikuwa wakikusanyika pamoja kama familia moja, na kila mmoja alileta vitu vyake vyote miguuni pa Mitume, nao Mitume wakawagawia watu kulingana na mahitaji yao, na maandiko yanaonesha hapakuwa na mtu asiyetimiziwa uhitaji wake kwa sababu waligawiwa kulingana na mahitaji ya Mtu.

Swali unalopaswa kujiuliza ni **Je, kama watu waliuza mali zao na wakaleta fedha miguuni pa mitume ili zigawanywe kulingana na mahitaji, mtu aliwezaje kupata sehemu ya kumi ili amtolee Mungu?.** kwa sababu kama vitu vyote ni shirika basi hapakuwa na mtu mwenye kitu chake binafsi. kwa mantiki hiyo utoaji wa Fungu la kumi unakosa nguvu bila sheria na bila maelekezo ya Mtume wala Nabii. 

**FUNGU LA KUMI SIO SEHEMU YA MATOLEO KWA MKRISTO.**


### Taratibu za wokovu kwa matendo ya mwili (Sala ya Toba na Ubatizo wa Maji)

**KUONGOZA SALA YA TOBA KWA WAAMINI WAPYA, MAFUNZO YA KUNENA KWA LUGHA, KUSHIKA UBATIZO WA MAJI**

### KUONGOZA/KUONGOZWA SALA YA TOBA.**

Sala ya toba imekuwa ni kama kanuni ya kwanza kwa muamini mpya katika kumjua Yesu Kristo, sala hii inaendelea kupata umaarufu mkubwa na kuonekana kana kwamba ni utaratibu sahihi wa kumwendea Yesu Kristo. kinyume na mafundisho ya Mitume  ***Efeso 2: 1 -- 10, Warumi11: 1 -- 6,Warumi 3: 24, Tito 3: 3 -- 10.*** Wokovu wa matendo ni mtego wa sgetani kwa waamini wa Yesu Kristo. Ndio maana unaweza kumkuta mtu anasema nina miaka kadha wa kadha katika wokovu, hii ni kwa sababu ni jambo aliloliratibu na kuliamua yeye mwenyewe, wala sio tena uweza wa Mungu kwa Msaada wa Roho Mtakatifu. Yesu akamwambia Nikodemu, **"Je, unaweza kuona upepo unapovuna unaanzia wapi au unakwenda wapi?, lah! hasha bali unauhisi, vivyo hivyo azaliwaye Rohoni hana mwazo wake wala mwisho."** maana yake ni kwamba, hakuna mwanzo wa kusema leo au kesho au jana nilizaliwa Rohoni (Mara ya pili) bali utakacho kihisi ni uweza wa Mungu kwa nguvu za Roho mtakatifu atakayejazwa ndani yako). **ROHO MTAKATIFU NDIO UTHIBITISHO WA KUZALIWA MARA YA PILI SIO SALA YA TOBA.**

### MAFUNDISHO YA KUNENA KWA LUGHA.**

Moja ya kituko na ulaghai uliojipenyeza katika fundisho la leo katika mikusanyiko na pia mikutano ya Imani ya Kikristo, ni kuwafundisha watu namna (style) za kuwawezesha kunena kwa lugha. fundisho hili sio kificho wala aibu tena bali imekuwa jambo la kimkakati kuwafanya watu waamini wamejazwa Roho Mtakatifu. Maandiko yanasema "Mitume walipojazwa Roho Mtakatifu wakaanza kila mmoja kunena kwa lugha mpya asiyoijua", na hata wale walioamini baadaa ya hao mitume kuwahubiria wakajazwa Roho mtakatifu na kuanza kunena kwa lugha mpya. hakuna mahala Biblia imefundisha au kuandika kwamba yupo mtume au nabii au mwalimu alifika akawahubiria watu habari za Yesu Kristo kisha walipoamini akawafundisha kunena kwa lugha. Kwa sababu kunena kwa lugha ni karama mtu anayopewa kutoka kwa Mungu, kama ishara mojawapo ya nguvu za Mungu, na ishara za kujzwa Roho Mtakatifu zipo nyingi sio ya Kunena Kwa lugha pekee. Hivyo mtu anapojaribu kumfundisha mwingine kunena kwa lugha ni kuchukua utkufu wa Mungu kuwa utukufu wake mwenyewe. 

**MAFUNDISHO YA KUNENA KWA LUGHA NI ULAGHAI NA IBADA YA SHETANI.**

### UBATIZO WA MAJI.**

Wengi tunaamini na tunasoma ya kwamba upo ubatizo, na ubatizo unaanza kuonekana katika vitabu vya Agano jipya, na ubatizo haukuanza na Yesu Kristo bali wapo waliobatizwa kabla yake. aliyepewa ujumbe wa ubatizo wa kwanza ambao ulikuwa ubatizo wa Maji kwa mujibu wa maandiko ni Yohana Mbatizaji, aliyetangulia katika huduma kabla ya masihi Yesu Kristo. Yeye aliwabatiza watu katika maji ya mito ikiwemo Yordani. Alikuwa anafanya ubatizo kwa ajili ya Toba, watu walimwendea na kutubu dhambi zao na kisha akawabatiza katika maji. Hivyo kupitia Yohana watu wa Israeli waliyarejea maandiko na kuona kwamba ilitabiriwa kwamba atakapokuja masihi, moja ya jambo atakalolifanya ni KUBATIZA. Mambo mengine ilikuwa ni pamoja na kuikomboa Israeli kutoka katika utumwa pamoja na Kuwakomboa watu kutoka katika dhambi zao.

Kufuatia kubatiza kwake Yohana watu haswa wasomi, wenye mamlaka, waandishi pamoja na viongozi wa Dini walimuuliza **Je, wewe ndiwe Kristo?.** walimuuliza swali hili kwa maana walisoma ya kwamba Kristo atakapokuja ndiye atakayebatiza, lakini Yohana aliwajibu akiwaambia **"Mimi siye".** Wakamuuliza **Kama wewe siyo Kristo mbona basi wabatiza?.** Akawajibu akawaambia **"Mimi nawabatiza kwa maji, kwa ajili ya toba, lakini Yupo yeye ajaye nyuma yangu naye alipaswa kuwa mbele yangu, yeye atawabatiza kwa Roho mtakatifu."** 

Rejea (***Marko 3: 1 -- 8. Mathayo 3: 1 -- 17.***) Huo ndio ubatizo wa Maji wa Yohana kwa ajili ya toba kwa Israeli.

**Ubatizo wa Yohana kwa Yesu Kristo.**

Baada tu ya kubatizwa kwake Yesu na Kuanza kazi yake, katika kitabu cha ***Luka 12:50,*** Yesu anasema ***"upo ubatizo nipaswao kubatizwa, nami nina dhiki kama nini hata utimizwe."*** maneno haya yanatafsririwa katika ***Luka 22: 44*** ambapo panaelezea dhiki aliyokuwa akiisema. 

Katika kitabu cha **Marko 10:38.** Yesu anasema ***"Hamjui muliombalo, je,mwaweza kukinywea kikombe nikinyweacho au ubatizo nibatizwao mwaweza kubatizwa.?"*** Katika maandiko hayo unaweza ukapata maswali mengi sana kwamba ubatizo wa Yesu aliokuwa akiulenga ni upi?. Je, ni ule wa Yohana.?

Nachelea kusema hasha sio ule wa Yohana, kwa sababu ubatizo wa Yohana wayahudi wote waliujua na wengi waliuamini na walibatizwa, hata Yesu mwenyewe alibatizwa. Sasa ni ubatizo upi ambao unampa dhiki katika kutimizwa kwake?, huku akiwauliza baadhi ya waliomuamini kama wanaweza kubatizwa ubatizo atakaobatizwa.? 

**MASWALI HAYA YANAASHIRIA UPO UBATIZO YESU ALIOKUWA AKIUSEMEA NAO NI MATESO NA KIFO CHAKE.**

Tukimalizia habari ya ubatizo ni dhahiri kwamba tunaweza tukajifunza kwa Mitume kwa kile walichokuwa wakikiishi baada ya Yesu kukufuka na Kupaa kwenda mawinguni. ***Matendo ya Mitume 19:1 -- 7, Wakolosai 2:12.*** Yesu hakuwahi kubatiza mtu yeyote ubatizo wa Maji. ***Yohana 4:1 -- 3.*** Yesu Kwa kuyatambua kwamba yatakuja mafundisho yenye mashaka juu ya ubatizo, kwa sababu wengi waliuzoea ule ubatizo wa Yohana (ubatizo wa maji), alipokwisha kufufuka aliwaambia wanafunzi wake.

**"ENENDENI MKAWAFANYE MATAIFA KUWA WANAFUNZI, MKIWABATIZA, KWA JINA LA BABA NA MWANA NA ROHO MTAKATIFU."**(**Mathayo 28:18 -- 20**). Huo ndio ubatizo wa Kristo na sio ubatizo wa maji uliokuwa wa Yohana i kwa ajili ya toba, zaidi ni kwamba ubatizo wa Yohana Uliandamana na Maungamo ya dhambi, sio kujazwa Roho Mtakatifu.

**KUTUMIA MANENO YA YESU KRISTO KATIKA UBATIZO WA YOHANA NI SAWA NA KUWEKA DIVAI MPYA KWENYE KIRIBA KUUKUU.** Yesu alitengeneza Imani moja, ubatizo mmoja kwa Mungu mmoja. ***Waefeso 4:5.***

### Taratibu za mafundisho ya maandiko.

**KUFUNDISHA IMANI, MAFUNDISHO YA NDOA, BIBLIA KUWA MBADALA WA ROHO MTAKATIFU, KUTUKUZA MIUJIZA BADALA YA UTAKATIFU.**

### IMANI

Moja fundisho lililoenea kwa wingi pia ni fundisho la IMANI. kwa kweli mimi binafsi huwa najiuliza ninaposoma Biblia je, huwa naelewa maandiko au nami pia kuna mahali biblia yangu inakosea?.  Kwa swali hilo mara kadhaa limenifanya niwe natafuta Biblia tofauti ili nijaribu kuoanisha mistari kusudi kama kuna makosa ya Mchapaji basi nisaidike. Lakini ninachokisoma ni kitu kimoja katiaka biblia zote. Swala la Imani kuwa somo ni elemu inayokua kwa kasi sana na ninaamini kati ya wale watakaosoma makali hii, basi yawezekana umewahi kusikia au hata pia kufundishwa/kufundisha somo hilo.

Swali kubwa ninalojiuliza ni ...

1. **Kama imani ingefundishwa kwanini Yesu asingeanza na somo la Imani kwa wanafunzi wake kusudi wasimpe taabu mbeleni.?**
1. **Kama Imani inafundishwa kwanini Yesu hakumfundisha Petro imani badala yake Alimuombea Petro kwa Mungu kwamba Imani yake isitindike?.** ***Luka 22:31 -- 32.***
1. **Kama imani inaweza kufundishwa watu wangapi walitendewa mambo mema na Yesu kwa sababu ya Imani zao lakini hawakuwahi kuwa wanafunzi wa Yesu.?**
1. **Kama imani inafundishwa kwanini mwanafunzi mmoja alimwambia Yesu tuongezee imani?, Kwanini asimwambie tufundishe kuamini/kukuamini?, ni dhahiri hata wao walijua Imani ni karama na sio somo.**

Kwa maswali hayo nawiwa kusema kuwa. moja ya fundisho batili na la kishetani ni fundisho la IMANI. Kwa sababu imani ni karama ambayo mtu hujaaliwa kama vile ilivyo neema ya Wokovu, hakuna mtu anayeweza kuamua kwa nafsi yake kuokoka, bali ni Kuokolewa kwa Neema ya Yesu Kristo. Sasa nikiona nyakati za leo Mtu anafundisha au anafundishwa HATUA ZA KUWA NA IMANI, nagundua ni kwa kiasi kikubwa sana Ulaghai wa Ibilisi umeingia Mahala patakatifu. 

Wapo watu waliambiwa na Yesu "enenda zako na ukapokee sawasawa na imanai yako", na wengine akawaambia "Imani yako imekuponya", wengine akawaambia "sijaona Imani kubwa kama hii katika Israeli", na hawa wote hawakuwa wanafunzi wake. Lakini ni mara nyingi aliwaambia wanafunzi wake "Amin, Amini nawaambia", maneno haya yanamaanisha wapo waliokuwa na mashaka juu ya yale aliyokuwa akiwaambia ndio maana alirudia mara kadhaa kuyasema maneno hayo. 

Sehemu nyingine anawaambia wanafunzi "nitawavumilia mpaka lini kwa Kutokuamini kwenu", na zaidi anasema "Ninyi mkiamini mtayafanya makuu kupita haya", mwanafunzi mmoja akamwambia "tuongezee imani", Yesu akamjibu "Mngalikuwa nayo ndogo kama chembe ya Hardali". Maana yake hawakuwa na Imani yakuwezesha kuyatenda mambo ambayo Yesu aliyatenda. Wakati Yesu akitembea juu ya Maji, Simoni Petro akamwambia "Rabi niruhusu nije", Yesu akamwambia "kama unaamini shuka chomboni njoo".

Ndugu zangu, tumuombe Mungu atusaidie kuyakemea na kuyakosoa mambo kama haya ambayo yanatafuta utukufu wa watu na sio utukufu wa Mungu. Ni laana na kufuru mbaya kuchukua kazi ya Mungu na kuifanya kuwa kazi ya mwanadamu, zipo kazi Mungu alizotuamuru tufanye ila tumeziacha na tumeanza kuingiza maarifa ya wanadamu na kuyaabudu kwa jina la Yesu.

**Kazi tulizoamriwa kuzifanya**

Kazi tuliyopewa ni kuwafundisha watu, kuwafunulia maandiko na kuwapa neno la Mungu, kuwafanya wawe wanafunzi wa Yesu Kristo, kuwabatiza kwa ubatizo wa Yesu Kristo, aliyouagiza kwamba mkawabatize kwa Jina la Baba na Mwana na Roho Mtakatifu. Kazi zetu ni kuwaombea wagonjwa na kuwasaidia wenye mahitaji, Upendo kati ya ndugu, lakini hasa kuwapenda hata wale wabaya wenu. Kazi zetu ndi kutumikiana kwa heshima na kuishi maisha matakatifu mbele za Mungu na Wanadamu. Kutii mamlaka na Kuwaombea wakosefu wapate kuokolewa.

### HILA ZA IBILISI ZINAYOENDEA KWA JINA LA YESU.

- MEZA YA BWANA KATIKA MAKUSANYIKO (SAKRAMENTI) MKATE NA DIVAI.
- FUNDISHO LA UBATIZO WA MAJI KAMA ISHARA YA KUZALIWA MARA YA PILI (WOKOVU).
- KUONGOZA/KUONGOZWA SALA YA TOBA.
- BIBLIA KUFANYWA KIONGOZI KWA WAKRISTO.
- MAFUNDISHO YA SADAKA ZA UKOMBOZI, KUFUTIWA LAANA ZA UKOO NA MIKOSI, KUBARIKIWA.
- KUAMINI NGUVU ZA MUNGU KUPITIA ISHARA ZA MIUJIZA PEKEE PASIPO MAISHA YA UTAKATIFU.

Hizo zote nilizoorodhesha hapo juu, ni ibada za sanamu na machukizo na makufuru mabaya Mbele ya Mungu wetu, hatuna budi kuishi kwa kutegemea hekima ya Mungu na sio kufuata maarifa ya kibinadamu juu ya mambo yamuhusuyo Mungu. Kwa kuvifanya vitu hivyo kuwa ndiyo ibada kumesababisha watu kutokujitoa nafsi zao katika kuifanya ibada iliyo ya kweli mbele ya Mungu.

- Kwa kufanya Majengo makibwa na kuwaaminisha watu kuwa ndiyo Kanisa tumefanya watu wasiliheshimu kanisa la kweli ambalo ni nafsi zao.Na kuanza kusujudu na kuyaheshimu majengo.

- Kwa kufanya Mkate na Divai kuwa damu ya Yesu, tumefanya watu wasujudie na kujitakasa mbele ya vitu visivyo na uhai wala visivyoweza kuokoa.

- Kwa kuwafundisha watu kutoa sadaka za Ukombozi na kufutiwa laana zao, tumefanya watu wasimuelekee yesu na kuanza kutafuta mali ili kwa hizo waondolewe shida zao na kwa kutoa kwao wapate mali zaidi.

Haya yote watu wanayaamini na kuyafanya mambo hayo kuwa matukufu, Kuamini kwako sio tatizo tatizo ni kwamba unaamini imani gani?. Imani itokaanayo na Mungu au Imani itokanayo na maagizo ya wanadamu?.

Ndugu zangu tumuheshimu na kumwamini Mungu mmoja na kushukuru kwa upendo wake kwetu hata akatutengenezea njia ya kupatana naye kupitia kifo cha mwanaye mpendwa, naye ndiye Bwana wetu Yesu Kristo, na akatupa zawadi ya kuwa wana wa Mungu kwa njia ya Imani yaani kumwamini Yesu Kristo, na kutupa uwezo wa kuishi maisha ya utakatifu na yenye kumpendeza yeye kwa njia ya msaada wa Roho Mtakatifu.

### MAFUNDISHO YA NDOA.

**"Ndoa na iheshimiwe na watu wote."** Ndivyo ninavyoweza kuanza makala hii, na katika makala hii sitaangazia ubaya wa mafundisho ya ndoa, bali nitaangalia makanisa ya leo yalivyo hodhi Ndoa kuwa mali ya makutano badala ya kuiacha kuwa mali ya wanandoa. Nazungumza hivyo kwa kuzingatia mafundisho yanayoenea na yamechukuliwa kuwa nikawaida na ndiyo utaratibu, ila athari yake ni mbaya sana, kwa sababu pameibuka fundisho linalowapa watu maelekezo kwamba, kama Kanisa (makutano/jumuia/taasisi) halijaridhia basi hiyo siyo ndoa halali na kwamba haina baraka mbele za Mungu. jambo hili haswa ndilo lililonivuta kuandika juu ya Ndoa katika makala hii.

Mambo matatu nitakayo angazia kwa urefu....

1. Muumini kushawishiwa kwa kutumia jina la Yesu, kuingia katika ndoa na Muumini wa Imani moja naye.
1. Muumini mpya kutenganishwa na mwenzi wake baada ya kuamini Imani/Dhehebu/Dini nyingine.
1. Ndoa inapata kibali kwa Mungu, kwa kufungiwa kanisani.

Mambo haya niliyoyaorodhesha hapo juu ndicho haswa chazo kilichonisukuma moyoni na kunilazimu kuyaandika. Ukweli sio mambo mageni masikioni pa wengi, kwa sababu kama halijakukuta wewe binafsi basi yaweza kuwa ndugu au kama sio Ndugu basi yaweza kuwa mtu unayemfahamu au hata kusikia kama soga kupitia watu wengine.

Unaweza kujiuliza kwani kuna ubaya gani endapo mtu mzima mwenye akili timamu, kwa hiyari yake pasipo shururi, ameamua kukubaliana na mapendekezo au ushauri wa mtu mwingine aliouona kufaa kwa maisha yake?.

Hakika hakuna tatizo endapo mtu mwenye utashi mzuri akiamua hivyo, kwa maana hapatakuwa na majuto na manung'uniko mbeleni wala hapataibuka lawama kwa yeyote, pia hapatatengenezeka migogoro ya kijamii.

Lakini linapokuja suala la mtu aliyeshawishiwa kwa njia ya Imani fulani kufikia uamuzi wowote kati ya haya niliyoyaandika hapo juu, basi tarajia pataibuka mgogoro wa kiimani au mgogoro wa kijamii. Kwa sababu dunia tunayoishi imechanganyika sana, ni tofauti na miaka ya nyuma kwamba ulikuwa huwezi kukuta makabila au imani za kidini na madhehebu yamechangamanisha watu wake katika jamii moja. ila kwa sasa ni jambo la kawaida wala halileti ghasia katikati ya watu kama hapo awali.

Tamaduni zimeingiliana na imani zinavumiliana kwa tofauti zao za kimitizamo juu ya mambo. Lakini tunapozungumzia ndoa tunagusa eneo ambalo linaunganisha jamii kwa urahisi zaidi kuliko Imani. Linaunganisha jamii kwa matendo ya dhahiri kuzi dini na hata kuzidi mila na desturi za kikabila. Ndio maana ndoa inabaki jambo ambalo elimu yake inapatikana kwa kuishi na sio kwa mafundisho ya kitabu au sheria na Adhabu.

Sasa nigusie masuala ambayo nimeyaorodhesha hapo juu.

**Muumini kushawishiwa kwa kutumia jina la Yesu kuingia katika ndoa na Muumini wa Imani moja naye.**

Jmbo hili liliibuka japo kwa kiasi lilipingwa na watu likafifia, lakini kufififa sio kuisha/kufa, ni jambo ambalo lipo na linaweza kustawi wakati wowote katikati ya jamii zetu, binafsi nalipinga kwa sababu ya hila iliyojificha ndani yake.

- Kama Moyo wa Mtu umemridhia mtu asiyeamini, kwa nini litumike Jina la Yesu kumtenga naye?.
- Kama Mtu anaweza kuwa na amani na furaha na akaendelea kudumu katika kumcha Mungu hata kama yupo na Mtu asiyemuamini Yesu, kuna tatizo gani wakiishi pamoja katika Ndoa?.
- Kama kuoa/Kuolewa na Muumini/Muamini mwenzako ni suluhisho, mbona migogoro ya Ndoa ya wenye Imani moja ni mingi zaidi ya hao wanaoitwa wasioamini 

**(Ushahidi ni Kesi za mashauri ya Ndoa, Talaka na Mirathi.)**

Mapendekezo yangu ni kwamba, kama mtu anaishi maisha yampendezayo Mungu na anamtumaini Mungu na kumtumikia, basi Mungu atamletea mwenza wa kuendana naye.

**VIKWAZO KATIKA KUCHAGUA MWENZA WA NDOA**

1. `**Kutafuta Mwenza unayemuwaza kichwani kwako:** Huyo aliyeko kichwani kwako hayuko duniani,unachopaswa ni kuchukua malighafi inayoweza kutengenezeka kumpata huyo aliyeko kichwani mwako.

1. `**Kutafuta mwenza kwa kutazama maisha ya wakati ulionao:** Kosa lingine ni pale watu wanapotazama matakwa yao kwa wakati walionao na kusahau kwamba kuna muda wa mahitaji utakuja,hivyo wanajikuta wanatafuta wenzi wanaowataka na sio wale wanaowahitaji haswa wakati wa mahitaji.

1. `**Kutafuta mwenza kwa fahari ya macho na ubora wa mazingira ya nje:** Wanadamu tumeumbiwa macho ya nje ya kutazama maumbo na masikio ya sauti na ngozi ya kuhisi na kinywa cha kunena,hivyo ni rahisi kuhadaiwa na vitu hivyo wakati tunapofanya machagua ya wenza tunaowahitaji,wengine huadaiwa na sauti,wengine muonekano,wengine hisia na wengine kwa maneno ya ulaghai.

1. `**Kutafuta mwenza kwa kulinganisha kwa hulka zake na za mwingine:** Wengi ni rahisi kujikwaa kwenye mtego huu,kwamba unampata mte unajenga ukaribu naye upate kumtambua,ila unaanza kumpima kwa kutumia watu wengine,mfano kaka,baba,mama, au baadhi ya mahusiano uliyowahi kuwa nayo kabla(tabia hii imeshamiri kwa nyaka hizi) na unaacha kipimo kizuri ambacho ni kulinganisha hulka zake na za kwako.

**Muumini mpya kutenganishwa na mwenzi wake baada ya kuamini Imani/Dhehebu/Dini nyingine.**

Ni kawaida katika makanisa ya Leo ukishiri katika makusanyiko na taratibu zao za ibada,basi ikiwa umewaamini fundisho lao ni rahisi kukutana na mafundisho yanayosema.. *"Kama umeolewa na Mumeo,au kama umeoa na Mkeo hasali pamoja nasi basi unapaswa umuache kwa maana wewe ni mwenye haki hauwezi kufungwa nira moja na mwenye dhambi,*" Fundisho hili sio tu kwamba ni la uongo bali ni lakishetani,kwa maana hata katika maandiko ya Bibli,imekataza kwa mtu aliyeongoka/aliyezaliwa mara ya pili,kama ameo au ameolewa maandiko yanasema asimuache mkewe au mumewe **1Wakorintho 7 :8 -- 16.**

Hivyo kwa maandiko hayo nadhani yanatosha kutoa ufahamu juu ya yale yampasaye mtu alipokombolewa katika hali ile Yesu Kristo aliyomkuta nayo.tusiwaingize watu katika dhambi na mitego ya Ibilisi kwa fundisho lisilopatana na kweli ya Mungu.

**Ili Ndoa ipate kibali kwa Mungu,basi lazima ifungiwe kanisani.**

Kwa kusoma mistari ya Biblia niliyoiweka hapo juu ni dhahiri kwamba,ndoa Mungu anaitambua kwa hali ya mtu aliyonayo,ikiwa ni ya Mila,au Kisheria (isipokuwa sheria iwe katika kuwafungamanisha watu kwa maisha yote),ikiwa ya Dini au hata kama ni ndoa ya ridhaa ya moyo wa wanandoa pekee bado zinabaki kuwa ndoa halali mbele za Mungu.Kwa maana kinachoridhia mke au mume ni moyo,na mioyo ikiungamanika kwa ni ya kweli sio lazima wanadamu waithibitishe ila yupo Mungu aangaliaye moyo ndiye ajuaye nia za watu,naye anasema **"Alichokiunganisha Mungu mwanadamu asikitenganishe"** hivyo anayeunganisha mioyo ni Mungu na sio mwanadamu kwa matendo ya mwili.

Watu wengi kwa kufuata hofu ya fundisho la Kanisa wameishia kufanya machukizo mnele za Mungu kwa kubatilisha au wakati mwingine kuziua ndoa halali ambazo Mungu aliziridhia na kuwaingiza watu katia uzinzi kwa Juna la Kanisa la Yesu Kristo.Hivyo ni batili na sio halali kuwatenganisha watu waliorifhiana kuisha katika maisha ya Ndoa kwa sababu za Kiimani na ufinyu wa Fikra katika kuyatambua Maagizo ya Mungu.

**KATIKA BIBLIA HAKUNA MSTARI UNAOONESHA KULIWAHI KUFUNGISHWA NDOA KANISANI AU HEKALUNI ILI IWE IMEPATA KIBALI KWA BWANA MUNGU.**

### MAFUNDISHO YA BIBLIA KUWA NENO LA MUNGU NA KUWA KIONGOZI KWA WAKRISTO

Moja ya neno jepesi na rahisi kutamkwa ni kusema maneno haya mawili....

1. `**Biblia ni neno la mungu**

1. `**Biblia ni kiongozi kwa wakristo**

Maneno hayo ni ya kawaida tu na unaposoma makala hii unaweza kujiuliza kwani kuna tatizo gani?na pia unaweza kwenda mbele zaidi na kusema kwa si ukweli kwamba wakristo tunafuata kilichoandikwa katika bibli na kwamba yaliyoandikwa humo ni maneno ya Mungu.

Napenda ni anze kwa kuweka mambo mawili wazi kabisa na kwamba ni hakika na hayana sha ndani ya Moyo wangu katika Kristo Yesu.**"BIBLIA SIO NENO LA MUNGU,NA PIA BIBLIA SIO KIONGOZI KWA WAKRISTO."** 

***Je, Neno la Mungu ni lipi basi kama sio hayo yalioandikwa katika Biblia?.***

Neno la Mungu halikai katika Makaratasi,bali linakaa katika Mioyo na fahamu za watakatifu wake na linatoka kupitia vinywa vya watakatifu wake nao ni hao **(Mitume,Manabii,Waalimu,Wachungaji na Wainjilisti)**.

Kisha wapo watu wengine ambao wanapewa karama na Hekima kutoka kwa Mungu,wao wanafanya kazi ya kuyakusanya yale yote yaliyonenwa na hao watakatifu wa Mungu na kuyaweka katika maandisi kisha kuyatunza na kurithisha vizazi hadi vizazi.Hivyo haya yote tuyasomayo ni maandiko,Maandiko yanayoelezea habari za historia ya Wanadamu toka kuumbwa kwake hat nyaka za mababu zetu waliopita kale kale,Kwa bahati nzuri pia yapo maneno ambayo yalinenwa na manabii yakiwa yatabiri mambo yajayo,na kwa hakika mimi na wewe ni mashuhuda wa baadhi ya yale yaliyoandikwa na tunayaona yakitokea katika zama zetu.

Maandiko hayana ubaya yakitumika vizuri,yakitumika kwa nia ile ile ambayo Mungu aliikusudia wakati anasema na watumishi wake,ila maandiko hayo hayo yakiwekwa fikra na elimu za binadamu yanapoteza shabaha na lengo ambalo lilikusudiwa na Mungu wakati anatoa ujumbe wake.Kwa ufupi katika maandiko tunapata Unabii,Ufunuo na Mafundisho.

Kwa kusema hivyo ninamaanisha ni kosa kubwa sana Kuyaita Maandiko Neno,Kwa maana ni kumfanya Mungu kana kwamba hawezi tena kutenda wala kuwaongoza wanadamu bali anategemea maandiko yawaongoze watu.Ni kufuru na ni nia ya Ibilisi kuwataka watu wayaabudu maandiko badala ya kumwabudu Mungu kupitia Roho Mtakatifu tuliyepewa kama kiongozi wetu.

Ndugu zangu, katika maandiko pia yapo mawazo na maneno ya watu,tena sio watu tu bali watu waovu kabisa waliofanya na kusema makufuru mbele za Mungu.Pia zipo nyaraka kama za Mtume Paulo alizokuwa akitanabaisha waziwazi kwamba **"haya niyaandikayo sio ya Bwana Mungu nali ni mawazo yangu."**Mfano **1Wakorintho 7;6 na 12.**

- **BIBLI NI MAANDIKO** 

- **NENO LA MUNGU LINAKAA MWA MCHA MUNGU** 

- **MAANDIKO YANAYO MAWAZO YA WATU HASA YA HAO WANAYOYAANDIKA**, ***Mfano wanaweza kupanga kitabu gani kianze kipi kifuate,au jina gani litumike hapa na lingine liachwe,au tuweke neno gani linaloweza kueleweka na lipi tusiliweke***.Au maneno yepi yaliyonenwa tuyaandike na yepi tuyaache Mfano ***Bilia inasema yapo mambo mengi ambayo Yesu aliyafanya lakini hayajaandikwa*** hivyo hata hayo yalioandikwa ni dhahiri ni yale yaliyoonekana kuchaguliwa na **Yohana 20:30 -- 31.**

- **NENO LA MUNGU HALIPANGILIWI NAMNA YA KUJA** Kwa maana linakuja kwa nguvu na uweza wa Mungu na hakuna mcha Mungu anayeweza kuamua katika ujumbe wa Mungu niseme upi na niache upi.

- **MAANDIKO HUSOMWA** husomwa kutoka katika vitabu,

- **NENO LA MUNGU HUNENWA kutoka kinywa cha Mtumishi wake**
Hivyo tunapoifanya Biblia kuwa Kiongozi cha wakristo,ni kuondoa uweza wa Roho Mtakatifu ndani yetu,maana hatutasikiliza maongozi ya Roho bali tutafata andiko linasema nini,na kwa hakika maandiko yamewapoteza wengi walioyafuata,Hata wakati Bwana wetu Yesu amekuja wayahudi na wakuu wa dini walikuwa wakichambua maandiko ili wapate mahala pa kumthibitisha Yesu,lakini hawakupata na hata walipoyaona waliifanya mioyo yao kuwa migumu.**1Petro 2:6,2Petro 1:20,2Petro 3:16,1Wakorintho 15:4,Warumi 15:4** Kwa hiyo mistari michache inaweza kukuthibitishia kwamba Biblia ni maandiko na sio Neno.

**MAANA YA NENO**

Yesu akwaambia ***"Ninyi mnayachunguza maandiko mkidhania kuna uzima ndani yake,nayo yananishuhudia mimi,nanyi hamtaki kuja kwangu muupate uzima"*** **Yohana 5:38 -- 40.**Maandiko hayo yasema wazi wazi kwa habari ya maandiko na Neno la Mungu.na katika **Yohana 6:63** tunaona sifa ya neno la Mungu kwa maana Neno linapotoka katika kinywa cha Mcha Mungu linatupa uzima.

Maandiko yanaweza kupotosha kama yakitumiwa vibaya,kudanganya,kulagai,kulaani,kutoa faraja za uongo,kutoa laana kinyume na makusudi ya Mungu,kama katika Kanisa la leo maandiko yanavyotumika kufanya uasi kwa Mungu kwa kufanya ibada za sanamu.Tumalizie kwa kusoma maandiko haya kama ushahidi wa hatari ya kutegemea maandiko badala ya Roho Mtakatifu. **2Wakorintho 3:6.andiko huua bali Roho huuwisha**.

**KUIPA BIBLI NAFASI YA ROHO MTAKATIFU NI IBADA YA SANAMU**

### KUTUKUZA MIUJIZA BADALA YA ROHO MTAKATIFU.

Imekuwa ni jambo ja kawaida kwa nyakati hizi za sasa,watu wengi kumwendea Mungu kwa sababu ya mahitaji yao binafsi bila kujali wala kuzingatia mahitaji ya Mungu katika maisha yao.Jambo hili limepelekea watu wengi kuangalia zaidi miujiza inayofanywa na wahubiri kwa lengo la kuwavuta wengi kuwa washirika katika makutano hayo.Lakini imetupasa sisi kufikiri kwa namna ya kibiblia na namna ya ukomavu wa fikra.

- Je, ni kweli kupitia miujiza ndio tunathitisha Mungu kutukubali?.
- Je, ni kweli kwamba miujiza ndio ishara ya uwepo wa Mungu katika maisha ya wahubiri hao?.
- Je, ni kweli kwamba miujiza kupitia kutendewa miujiza Mungu anasamehe makosa yetu?

Watu wengi wanaweza kuchanganya kati ya mambo hayo niliyoyaorodhesha hapo juu na yale ambayo yamekuwa katika fikra zao,lakini napenda tuangazie mambo kadhaa ili tuone na kujiridhisha kama kweli kuna mahusiano kati ya Miujiza na uwepo wa Mungu katika maisha yetu,na Mungu kuturidhia mbele zake.

Tukisoma katika Biblia tunapata kuona jinsi gani ambavyo watu tangu hapo kale walivyokuwa wakichanganya kati ya Miujiza na uwepo wa Mungu.Tofauti ni kwamba Sio kila muujiza unafanywa na Mungu,na sio kila muujiza basi haujafanywa na Mungu.Ni kweli kwamba wapo watumishi wa Mungu wengi tu ambao wanaishi kwa msaada wa Mungu kupitia maongozi ya Roho Mtakatifu,na wanafanya yale yote ambayo Roho wa Mungu anawaongoza kuwafanya.Lakini pia hao wanaoutumikia miungu wengine ni wengi zaidi kwa maana nao pia wanaishi kwa kufuata nia na tabia za miungu wao,nao wanatenda kazi zilezile ambazo miungu yao huwapa uwezo wa kuzitenda.

**Mathayo: 7: 12 -- 24**

***Basi yo yote myatakayo mtendewe na watu,nanyi watendeeni vivyo hivyo,maana hiyo ndiyo torati na manabii.Ingienikwa kupitia mlango ulio mwembamba,maana mlango ni mpana,na njia ni pana ieleayo upotevuni,nao ni wengi waingiao kwa mlango huo.Bali mlango ni mwembamba na njia imesonga iendayo uzimani nao waionao ni wachache.***

***Jihadharini na manabii wa uongo watu wawajiao wamevaa mavazi ya Kondoo,walakini kwa ndani ni mbwa mwitu wakali.Mtawatambua kwa matunda yao,je,watu huchuma zababibu katika miiba,au tini katika mibaruti?.Vivyo hivyo kila mti mwema huzaa matunda mazuri,na mti muovu huzaa matunda mabaya.Mti mwema hauwezi kuzaa matunda mabaya,wala mti muovu kuzaa matunda mazuri.Kila mti usiozaa matunda mazuri hukatwa ukatupwa motoni.Ndiposa kwa matunda yao mtawatambua.***

***Si kila mtu aniambaiye Bwana Bwana ataingia katika ufalme wa Mbinguni,bali ni yeye afanyaye mapenzi ya Baba yangu aliye Mbinguni.Wengi wataniambia siku ile,Bwana hatukufanya miujiza kwa jina lako,na kwa jina lako kutoa pepo,na kwa jina lako kufanya miujiza mingi?.Ndipo niwaambia dhahiri,sikuwajua ninyi kamwe,ondokeni kwangu ninyi mtendao maovu.Basi kila asikaye hayo maneno yangu na kuyafanya,atafananishwa na mtu mwenye akili,aliyejenga nyumba yake juu ya mwamba.***

Kwa kusoma mistari hiyo michache,tunaona kwamba Yesu mwenyewe aliyajua hayo mawazo na mitizamo ya watu.Kwa sababu Yesu anaangalia mioyo na sio kwa macho ya nje,na baada ya fundisho hilo watu walishangaa na kustaajabu kwa mafundisho yake,kwanini watu walistaajabu na kushangaa?,ni kwa sababu wengi wao waliamini kwamba kuyatenda hayo yoye ndio tiketi ya Kuingia mbinguni au ndiyo ishara ya kukubaliwa na Mungu.

Badala yake Yesu anasema kwamba ni yule anayetenda mapenzi ya Baba Yake aliyeMbinguni,kwa maana rahisi zaidi ni kwamba kutenda miujiza haimaanishi ni kibali mbele za Mungu,kwa maana hata waovu wanaweza kutenda miujiza,bali kuteda mapenzi ya Mungu haiwezekani kwa mtu muovu ispokuwa kwa msaada wa Roho mtakatifu.Na ili uwe na uweza wa Roho mtakatifu basi sharti uwe umepata uzao wa Mungu kwa njia ya Yesu Kristo.na ndipo Roho atakapokuwezesha kuyatenda mapenzi ya Mungu.

### Waovu wanaotumia jina la Yesu.**
 
Kwa sababu ya uhaba wa Neno la kweli la Mungu katika nyakati hizi za sasa,kumeplekea hata watu ambao wamekosa sifa ya kulihubiri Neno la kweli la Mungu,kuthubutu kuwalaghai watu na kuwaaminisha kwamba Yesu aliyewa kweli ni yule anayetenda kazi katika miujiza na kutoa mapepo,na wengu kugubikwa na unabii wa uongo,ambao kwa unabii wao wameuliza watu na kuwapumbza kiakili na mwishowe wengi wamejikuta wakipata hasara za mali na wengine kupoteza katisa matarrajio na mapenzi kwa Mungu,kwa kuona kana kwamba watuwote wenye kulihubiri Neno la kweli la Yesu Kristo kana kwamba wote hawafai/ni waongo.

Watumishi wengi wamekuwa na matendo na wakati mwingine maneno yasiyofaa sio tu mbele ya wanadamu bali hata mbele za Mungu,matendo hayo ni pamoja na wengi wao kuhusishwa mambo machafu ya giza,yaani kufanya masuala ya kishirikina ili kuwarubuni watu kwamba ni nguvu za Mungu.Wengine wakiwa wanashuhudiwa kuwa na tabia zisizofaa katikati ya jamii,wakiishi maisha ya uovu lakini bado wakiendelea kufanya huduma ya Kuhubiri Injili ya Yesu Kristo.

Matendo ya Nuru na matendo ya giza haviendani,wala hatutegemei kupata mambo mema kwa muovu,kama isivyowezekana kupata mambo maovu kwa mtu mwema,swali  la msingi la kujiuliza ni **Je,tunapaswa kuwaamini watenda miujiza kwamba ndio ishara ya Kuwa na Mungu ndani yao?.**

Ukweli ni kwamba hatupaswi kuamini nakufuata miujiza badala ya kutafuta maongozi ya Roho Mtakatifu,kwa sababu miujiza na kutoa mapepo sio tiketi ya kuingia mbinguni,maana pasipo huo utakatifu,hatuwezi kumuona Mungu.Kuwainua watenda miujiza na kuwapa hishima ambayo ilipaswa kupewa Yesu Kristo ni ishara ya wazi kwamba,hao wanajitafutia utukufu wao wenyewe na kwamba Roho wanayoitumikia sio ile iliyokuwa ndani ya Kristo Yesu,bali ni roho nyingine ambazo wanazitumikia.

Ndugu zangu kama tulivyoona imempasa muombaji yeyote afanyapo jambo lolote ikiwa ni maombezi,au kusafisha watu dhidi ya roho wachafu,basi afanye hayo yote kwa ajili ya utukufu wa Yesu Kristo.Kama kuna jambo lolote ambalo halimuinui Yesu Kristo basi lina ubatili tangu hapo,na halina kibali machoni kwa Mungu.Na ikiwa mtu anatenda Miujiza lakini hatendi mapenzi ya Mungu yaani haenendi mwenendo upasao wokovu,basi ni dhahiri kwamba ipo nguvu ambayo haitoki kwa Mungu inatenda kazi ndani yake,kwa maana Mungu hatendi kazi pamoja na muovu,bali hutenda pamoja na watakatifu wake,yaani wale wanaoyashika maagizo yake,na kumtii Roho wake.

**MIUJIZA PEKEE BILA UCHA MUNGU,NI MAYENDO YA UFALME WA GIZA.***

# MIONGOZO YA MAANDIKO.

Katika maandiko ya Biblia ni mara nyingi usomapo utakutana na maneno kadha wa kadha ambayo unaweza ukawa unapata tahayari kidogo kwa sababu ya kutokuyafasiri ipasavyo.Jambo hilo linatokana na kwamba watu wengi sio wasomaji wa Biblia mara kwa mara,na hata wale wanaosoma mara kwa mara wamejikita kusoma masomo yanayo jirudia rudia kwa maelekezo ya waalimu au viongozi wao wa dini.

Kusoma Biblia kaukupi uhakika wa kumjua Mungu,bali kunakupa uelewa wa habari za Mungu na wanadamu kwa nyakati tofauti tofauti toka kuumbwa kwa Ulimwengu pamoja na kuumbwa kwa Adam.Katika kusoma huko utakutana na maneno mengi ya kinabii na kitaaluma,ambayo yanahitaji Roho Mtakatifu kukufunulia ili uweze kuyaelewa.Roho ni mwalimu mzuri awezaye kukufundisha kutokana na uweza wa Mungu ambaye yupo ndani yako.Sio kosa kuwa na mwalimu au mchungaji anayekupa muongozo katika kusoma Biblia,ila kwa hakika ni lazima uwe na Roho mtakatifu atakayekufunulia mafumbo yaliyomo ndani ya kitabu hicho/.

Vile vile yeye afundisha hana budi kuwa na Roho Mtakatifu ndani yake ili kumsaidia kupata tafasiri sahihi katika kuwafundisha na kutoa miongozo kwa watu.Biblia pasipo Ufunuo wa Mungu ni sawa na kitabu cha kumbkumbu za kale pamoja na utabisi wa kinajimu.kwa maana hata hao watu wa kawaida katika mwili wanaweza kutengeneza na kutoa tafsiri za mambo yaliyofichwa kwa mafumbo ya kitaaluma.Basi imetupasa kumsihi sana Roho Kutuongoza wakati tunapokisoma au kujifunza kitabu cha Biblia.

Maandiko yaliyomo humo ni maneno ambayo Mungu aliyaweka katika vinywa vya watumishi wake na wakayasema katika Roho wa Mungu,hivyo ni vyema tukayasoma tukiwa tumeungamanishwa na Roho yule yule wa Mungu.Sio kosa kusoma Biblia ila ni kosa kuitafsiri Biblia kama upendavyo wewe mwenyewe,kwa maana yapo maneno ya unabii ambayo ukiyabatilisha kwa kutoa tafsiri isiyokuwa sahihi,basi unajibebea laana kwa kinywa chako mwenyewe.Hivyo ni vyema na bora zaidi kunyamaza kuliko kuweka maneno na tafsiri zako binafsi kwa ajili ya maslahi yako au kwa sababu ya ujinga wa kutokujua kwako.

## MAANDIKO BILA UFUNUO NI MAUTI.

**Luka 24: 44 -- 49.**

Yesu anawafunulia wanafunzi wake akili zao ili wapate kuyatambua maandiko,maneno hayo yana maana kwamba wanafunzi waliyajua maandiko hapo kwanza,ili kitu kikubwa na muhimu ambacho walikosa ilikuwa ni ufunuo,ndio maana Yesu Kristo baada ya kufufuka alipowatokea wanafunzi wake,moja ya jambo alilofanya ilikuwa kuwapa ufunu juu ya maandiko,ili kusudi watakapoyasoma wapate kuyafahamu kupitia Roho ya Ufunuo.

Na pale tunaposoma maandiko bila kuwa na ufunuo ndipo tunaambiwa **"andiko huua"** lakini pale tunaposoma kwa ufunuo **"Roho huuwisha".** Hivyo ndugu zangu nawiwa kusema katika baadhi ya chambuzi ninazoziweka hapa sio kwamba nimezitoa kichwani bali ni Roho alimvuvia Mtumwa wake **(ABDALAH MOHAMED KALUNDE)**,nami niliyeandika katika kitabu hiki nilizipokea kutoka kwake,naye akinifundisha na kunishuhudia nguvu na kweli ya Yesu Kristo hata kufikia kupewa kibali na Mungu kuandika Kitabu hiki.Kwa hakika ni shuhuda zenye nguvu na maisha ya kweli ambayo tulishiriki kwa msaada wa Yesu Kristo kupitia Mtumwa wake Kalunde.

### Baadhi ya miongozo ya kukusaidia kusoma maandiko.


BIBLIA inaandika kwamba **“Yeye asomae na afahamu”** hivyo ni dhahiri kwamba tutaposoma mambo yeyote aidha yenye marifa ya Kimungu au yenye maarifa ya kidunia,ili tuweze kupata hayo maarifa yaliyokusudiwa basi hatuna budi kuyafahamu hayo tuyasomayo,vilevile hatuna budi kuyatafutia uhakika yale tuyafahamuyo.

BIBLIA ni maandiko yaliyoletwa katika Roho ili tuweze kuyatambua basi imetupasa kuongozwa na Roho katika kuyapatia maana au kuyatafakari, la sivyo tutapoteza maana yote iliyokusudiwa,pia si maneno yakuyatafsiri kama mtu apendavyo mwenyewe,Mtume paul anaandika anasema “je mambo yaliyoandikwa kuhusu wanyama yaliandikwa kwa ajili ya hao wanyama? la hasha hayakuandikwa kwa ajili ya hao wanyama bali kwa ajili yetu sisi**” 1 wak;9:9** hivyo ndugu zangu tunapotoa waraka huu kwa hakika ni kazi ya Mungu katika maisha yetu na siyo maarifa ya kibinadamu,wala si kwa utashi wa mtu bali ni uweza wa Roho mtakatifu.

- **NOTE**

Mungu aliposema juu ya wanyama,mimea au vitu vingine hakuwa na maana ya vitu hivyo bali alivitumia kama mfano kusudi aweze kumfundisha mwanadamu.Yesu akwaambia makutano akisema**”nimesema nanyi mambo ya duniani hamkunisadiki je mtanisaidiki vipi nikisema nanyi mambo ya mbinguni?"**

Andiko jingine linasema **“wala pasipo mfano Yesu hakunena jambo”** kwa maana hiyo yapo mambo mengi sana ambayo yalisemwa kwa mifano ila watu wameyapokea kama mambo halisi, jambo ambalo linapoteza shabaha nzuri ya Rohoni na kuendelea kutuhubiria mambo ya mwilini.

Sehemu moja kaatika maandiko ya Biblia inasema wanafunzi walipokuwa katika faragha na Yesu wakamuuliza**“Bwana mbona unapokuwa na makutano unasema nao kwa mifano?”**Yesu akajibu akawaambia **ninyi mumebahatika kuzijua siri za ufalme wa Mungu nasema nanyi wazi wazi bali wao huambiwa kwa mifano ili watizame wala wasione na wasikie wala wasielewe".**

Hivyo ndugu zangu tunachojifunza katika mistari hii michache ya utangulizi tunaona uthibitisho kuwa MUNGU BABA na YESU KRISTO BWANA WETU walitumia mifano ili kufikisha ujumbe kwa wanadamu.Swali la msingi lingekuwa ni hili **Je,sisi nasi tuendelee kuishi kwa kufuata mifano?,** lakini je kama ndivyo Yesu alitumia mifano kwa ajali ya akina nani? Wanafunzi wake au makutano? (mataifa)? na kama ni kwa ajili ya makutano (mataifa),je sisi nasi ni wanafunzi wa Yesu au makutano?.

Na kama sisi tunakiri na kuamini kuwa ni wanafunzi je,siri hizi na mafumbo haya yataendelea kutumika mpaka lini? au tutaendelea kujihesabu kuwa wanafunzi wa Yesu pasipo kuenenda sawasawa na ishara za kiuanafunzi? na hizo ishara za kiuanafunzi ni zipi basi kama si pamoja na kuwa na hekima katika kila jambo?.maandiko yanasema **"Naye Bwana atawapa akili katika kila jambo"**.

Hivyo basi ndugu yangu tunapoenda kukisoma kitabu hiki na tumtangulize Mungu kwanza ili akatujaalie kuzifunua akili zetu ili tuweze kuyatambua makusudi na shabaha iliyopo katika fundisho hili.

**BWANA MUNGU atufunulie akili zetu tupate kuyatambua maandiko Amen.**

- Maji ya Mto ------
- Maji ya bahari -------
- Jangwa ------
- Nyika --------
- Nyoka -------
- Jiwe --------
- Majani mabichi ------
- Majani makavu ------
- Mti mbichi --------
- Mti mkavu ---------
- Chem chem ---------
- Nchi --------
- Mbingu -------
- Matope -------
- Udongo ------
- Nguruwe -------
- Punda ---------
- Kambale ------
- Ng'ombe ------
- Tai ------
- Vugu vugu -----
- Moto -------
- Baridi ------
- Mkate ------
- Divai ------

# UPOTOFU WA MAWAZO YETU MAZURI JUU YA MUNGU.

Watu wengi katika kizazi cha kale na hata kizazi cha sasa,tunayo mawazo yetu mazuri tuliyonayo juu ya Mungu,kwa bahati nzuri mawazo hayohayajatokana na kiburi au ujinga wa kutokupata taarifa,bali yametokana na taarifa isiyo sahihi tuliyoipokea/kuipata kutoka katika chanzo/vyanzo tunavyoviamini pasipo shaka yeyote.

Kupitia mawazo hayo tuliyonayo tumejikuta tukiyahubiri na kufundisha mambo ambayo wakati mwingine yanakwenda tofauti kabisa na maandiko ambayo tunayatumia kuhalalisha mahubiri au mafundisho yetu.Jambo hili tutaliangalia kupitia upotoshaji unaoendelea juu ya injili kwa njia ya mafundisho ya maandiko ya Biblia.Na zaidi tutaangazia mafundisho yaliyopotoshwa zaidi,na watu wengi wakayaamini mafundisho hayo na kuuacha ukweli wa maandiko yalivyoandika.
tumaini letu lingekuwa katika mashaka na hisia pasipo hakika Amen.)***



# SIRI ILIYOFUNULIWA NA KUPOTOSHWA.

Kitabu cha ufunuo wa Yohana,kinaweza kikawa moja kati ya vitabu visivyosomwa sana na watu wengu hasa waamini wa Imani ya Yesu Kristo.Jambo hili la kutosoma kitabu hicho halijatokea kwa bahati mbaya,bali ni mkakati wa kimahesabu ambao Ibilisi ameuratibu na nafanya mbinu zote kuzuia au kuwafunga watu fikra ili wasiweze kukifuatilia kwa ukaribu kitabu hicho.

Zipo sababu na njia nyingi alizozitumia Ibilisi kuzuia au kuwafumba watu fikra zao ili wasijishughulishe aidha kabisa au kwa nafasi ya kutosha kukitafakari na kujifunza mambo yaliyoandikwa humo.Katika Makala hii nitaanza na mbinu alizozitumia kuzuia au kuwafumba watu ili wasikizingatie sana kitabu cha Ufunuo,kisha tutamalizia na sababu za kuwafanya watu kukiacha nyuma kitabu hicho.

## Mbinu za Ibilisi.

Sio jambo geni kusikia mtu tena muumini akisema “Kitabu cha Ufunuo ni kigumu kukitafakari”,au kusikia mtu akisema “ Ufunuo ni kitabu chenye mafumbo ambayo mtu unaweza kujikuta ukimkufuru Mungu kama hutayaelewa”.Mbinu hii unaweza kuona ni kana kwamba inamashiko lakini sio kweli kwa maana kama Mungu alimfunulia mjumbe wake Yohana naye Yohana akaanza kwa kuandika “Kheri ayasomaye na yeye asikiaye maneno ya unabii huu,na kuyashika yaliyoandikwa humo kwa maana wakati u karibu”.

Kwa kusema kwamba kitabu hicho kina mafumbo mengi na kwamba kinaweza kukuchanganya,ni mbinu ya kimkakati kwa maana Ibilisi anajua ya kwamba katika kitabu hicho ndipo ilipo siri ya nguvu na hila zake,na pia ipo siri ya hatma yake,Ibilisi hawezi kuruhusu wala kukubali kirahisi mtu aweze kupa siri hizo kwa maana ndizo zinazomsaidia kuendelea kupata wafuasi katika dunia hii.

Ibilisi amwtumia watu mbalimbali na wenye nyadhifa mbalimbali ili kuhakikisha kwamba kusudi lake linasimama,na ataendelea kuwatumia watu hao hata pale yote yatakapotimia.Ukweli ni kwamba hakuna mtu katika Maisha ya mwili atendaye neno lolote isipokuwa kuna ngungu inayotenda kazi ndani yake.Na nguvu hiyo ni aidha ni nguvu ya Ibilisi au ya Mungu.Kati ya hizi falme mbili ni lazima mwanadamu awajibike kwa mojawapo.

Swali la msingi ni je,tunayoyasema na kuyafundisha yanamfanya mtu atende mapenzi ya Mungu kama ambavyo ilikusudiwa na Yesu Kristo?, pia tunapaswa kujiuliza je,tunajua hatma ya Maisha yetu pasipo kupata taarifa zinazohusu wakati ujao?, Na pia ukitaka kujua hatma ya Maisha ya ulimwenguni basi kasome kitabu hicho,kwa maana hata hatma ya Ibilisi ipo humo.

Huwezi kujutia wala kuchanganyikiwa kama Roho wa Mungu yupo Pamoja nawe katika kuyatafakari na kuyadadisi mambo ya ufalme wa Mung una ufalme wa Giza,kwa maana Mungu atakuwa nawe katika nyakati zote za kumtafakari kwako.Usitishwe wala usihadaike kwa hila za Muovu Ibilisi kwamba huwezi kuelewa yaliyoandikwa humo,kwa maana Mungu ameruhusu tuyajue hayo kusudi tujiandae na kujivika utayari kuyakabili yote ambayo hayana budi kutokea kwetu sisi Pamoja na ndugu zetu watakaokuwa Pamoja nasi katika Imani ya Yesu Kristo.

***(Mungu atulinde na kutuwezesha kuyatambua na kuyafahamu Yote yaliyo siri kwa uweza wake,na katika kuyafafanua na kuyachambua yaliyomo katika kitabu hiki, atupe Roho wake atuwezeshe kukimaliza kama kilivyokusudiwa na Mungu wakati wa kukileta kwetu kupitia Mtumwa wake Yohana Amen.)***

# MWANZO WA KITABU:  (Mateso na Amani ya shahidi)

## Mateso ya shahidi ………..

Mwanzo kabisa wa kitabu cha Ufunuo tunaanza kuona dhiki na mateso ya kuwa shahidi wa Yesu Kristo.Tunaiona dhiki hiyo na mateso hayo kupitia ushuhuda wa Yohana mwenyewe kwa maana ameandika kwamba 

***“Mimi Yohana, ndugu yenu na mwenye kushiriki Pamoja nanyi katika mateso ya ufalme na Subira ya Yesu Kristo,nalikuwa katika kisiwa kiitwacho Patmo,kwa ajili ya neno la Mungu,na ushuhuda wa Yesu.”***

Kupitia maneno hayo ya Yohana ni Dhahiri kwamba ipo gharama kubwa ambayo tunailipa na hatuna budi kuilipa siku kwa siku,katika kumshuhudia Yesu Kristo na kuyaishi yale yampendezayo MUNGU.Sio kwa sababu ya ubaya au dhambi zetu bali kwa ajili ya wangine wapate kuokolewa na kuwa mashahidi wa Yesu Kristo.Hivyo kuwa shahidi mwaminifu wa Yesu Kristo ni lazima ujue na ujiandae kubeba……………

**Lawama, Dhihaka, Matusi, Kejeli, Masimango, Kudharauliwa, Kutengwa, Kuteseka kwa namna mbalimbali kwa ajili ya Yesu Kristo.**Na hayo yote ndiyo tuyasomayo katika kitabu cha Ufunuo wa Yohana,na ndiyo tupaswayo kuyajua na kuyashika kwa maana hayana budi kutokea.

Katika kupitia mateso hayo hakika dhiki itakuwa kubwa siku kwa siku katika Maisha ya shahidi wa Yesu Kristo,na hakuna ahadi ya mateso hayo kumalizika ingali tupo duniani,bali ahadi ya mateso hayo kumalizika ni hata pale tutakapokufa tungali mashahidi waaminifu.Hivyo suala sio kumwamini Yesu na kuzaliwa mara ya Pili bali ni kuishika Imani na kuilinda hata Kufa.Hapo ndipo Faraja yetu ilipo yaani mwisho wa safari yetu katika wokovu na sio mwanzo wa safari.

## Amani ya shahidi …………

Ijapokuwa ni kweli kwamba tutapitia dhiki kuu,lakini tukiwa katika Yesu Kristo tutakuwa na amani,na hiyo ndiyo itakayokuwa tofauti kati yetu sisi tulio mashahidi wa kweli na wale ambao Imani yao wameweka kati vitu vya mwilini,Yohana akiwa katika dhiki kuu kwa ajili ya Neno la Mungu na ushuhuda wa Yesu Kristo,anaanza kwa kupewa “Amani.”Ili imfariji katika dhiki yake.

***“Yohana kwa yale makanisa saba yaliyoko Asia,Neema na iwe kwenu na Amani,zitokazo kwake yeye aliyeko,aliyekuwako na atakayekuja,na zitokazo kwa Roho saba walioko mbele ya kiti chake cha enzi,na kutufanya kuwa ufalme,na makuhani kwa Mungu,naye ni Baba yake;utukufu na ukuu una yeye hata milele na milele Amina”.***

Hivyo ndugu msomaji,ili tuweze kumudu mateso yaliyoko mbele yetu hatuna budi kupewa amani itokayo kwake yeye aliyeko,aliyekuwako na atakayekuja.kwa maana bila amani itokayo kwake basi hatuwezi kustahimili hayo yapaswayo kuja na kutukuta.Imetupasa kumuomba Mungu atuwezeshe kudumu katika Amani itokayo kwake ili tuyastahimili yale yajayo kwa ajili ya kulisimamia Agano la Mung una ushuhuda wa Yesu Kristo.

***(Mateso na dhiki ya kuwa shahidi wa Yesu Kristo hayawezekani kuyastahimili pasipo kupewa Amani itokayo kwa Mungu mwenyezi,na msaada wa Roho takatifu wa Yesu Kristo,Basi imetupasa kudumu katika kweli na Maisha ya utakatifu ili Mungu asituache peke yetu wakati wa dhiki kuu,na pia asituache tukaangamia kwa kushindwa kuilinda Imani tuliyoipokea ya Yesu Kristo Bwana wetu Amen.)***

# SIRI YA IBILISI ILIYOFUNULIWA

Katika kitabu cha Ufunuo wa Yohana,ndipo kulipofunuliwa siri na mbinu za Ibilisi anazozitumia kuwalaghai wanadamu na kuwafanya wengu kuwa wafuasi wake,katika kitabu hicho ndipo tunaona ni namna gani Ibilisi alikuwa akifanya kazi zake na alitumia watu kwa namna gani kukamilisha makusudi yake ya kuwapoteza wanadamu na pia ni kwa namna gani atatengeneza mfumo wa Kumpinga Masihi Mwana wa Mungu aliye juu na Bwana wetu Yesu Kristo ili watu wasiweze kupata sababu wala fursa ya Kumuamini (ROHO YA MPINGA KRISTO).

Sio jambo rahisi Ibilisi kuruhusu watu wazijue mbinu zake,wala hawezi kuliruhusu kirahisi kwa maana ni pale tu unapogundua silaha za adui na uwezo alionao ndipo unaweza kumshinda,hivyo Ibilisi hawezi kuruhusu watu wajue silaha wala uweza wake ili wasije wakatumia huo kumshinda.Hivyo Ibilisi ataendelea kufanya kila hila,na atainua watu wa kila namna wenye mamlaka na ushawishi mkubwa katika jamii,ili waendeleze mipango na kutimiza makusudi yake.

Atawapa watu hao uwezo mkubwa sana na kuwapa umaarufu na ushawishi usioweza kupingwa na mtu yeyote isipokuwa uwe ni mtu uliyewekwa chapa ya Yesu Kristo.maana pasipo uweza wa Mungu ndani yako hakuna awezaye kushindana wa kumshinda hila na mbinu zake,kwa maana anatumia uweza na nguvu zote za Mamlaka na Ushawishi wa akili za kibinadamu.

1. `Je,ni nani awezaye kushindana na Mamlaka (Serikali)?.
1. `Je,ni nani awezaye kuvumilia kutengwa na Imani yake (Dini)?. 
1. `Je,ni nani awezaye kunena kinyume na jamii yote inayomzunguka (Familia na wanajamii)?.

Hayo ndiyo maswali upaswayo kujijibu ili kujua kama unao uwezo wa kushindana na Ibilisi pasipo uweza na msaada wa Mungu.Pasipo Mungu hakika hakuna awezaye kumshinda kwa maana huko kote ndipo a lipoweka ufalme na nguvu zake,amewapa wafuasi wake Mamlaka za maamuzi,amewapa Wafuasi wake ushawishi mkubwa katika jamii,amewapa wafuasi wake nguvu za kusimamisha ufalme ambao utamwelekea yeye na kuwatenga wanadamu na Mungu na Zaidi kuwanyima wanadamu fursa ya kumwabudu Mungu wa kweli.

Iblisi aliyafanya hayo tangu kale,kuwapa wafuasi wake nguvu katika jamii ili aweze kuwapata wanadamu kwa hila,na katika kipindi chote siri na mbinu zake hazikuwekwa wazi ndio maana bado watu walianguka katika mitego yake,ila kwa kuwa Yupo mmoja aliyeshinda ilia pate kushinda tena kupitia wewe na mimi naye ndiye Yesu Kristo Mwana wa Mungu wa Pekee,yeye ametufunulia siri na hila za Ibilisi na namna ambavyo atatenda kwa wanadamu katika nyakati tofauti tofauti hata pale yatakapo timia yale yapaswayo kutimia.

Siri hizo zimefunuliwa kwetu ili tuzitambue na tujihadhari na hila hizo zitakapotujia,sio ili kwamba tuwe mahodari wa elimu bali tuwe macho kuzitambua dalili na ishara pindi zinapotujia,tusienende kama vipofu bali tuwe watu wanao ona.Tuzipinge hila za Ibilisi na kuzikemea ili zipate kushindwa.Haya yote yalifichwa huko awali ila sasa ametufunulia dalili zile na kwa hakika imetupasa kuzifahamu na kuomba msaada wa Roho Takatifu wa Yesu Kristo atusaidie kutulinda katika Imani ili tuzishinde,na tuwe mashahidi waaminifu hata Kufa kwa ajili ya kweli ya Kristo Yesu.

***(Siri imefunuliwa ili tuzitambue dalili na ishara za hila za Ibilisi na tuzipinge na kuzikemea Amen.)***

# UNABII WA KURUDI KWA YESU KRISTO.

Katika kuanza kwa maneno ya unabii wa kitabu,tunaona jambo kuu la pili baada ya mateso ya mashahidi wa Imani ya Yesu ni kurudi kwa Yesu Kristo.kwa maana imeandikwa ya kwamba……..
“Tazama yuaja na mawingu, na kila jicho litamwona,na hao waliomchoma,na kabila zote za dunia wataomboleza kwa ajili yake”.

Katika kutilia mkazo ya kwamba kila jambo linalo na litakalotokea hapa duniani katika nyakati zote za dhiki na mateso na taabu ya wateule wa Mungu,mwisho wake Yesu Kristo atarudi nah apo ndipo patakuwa na faraja ya waliovumilia na kuilinda Imani katika kipindi cha mateso na dhiki kuu,
Hivyo kurudi kwa Yesu sio nadharia ni jambo halisi tulitarajialo na kulisubiri kwa mud ana wakati uliopangwa,swali ni……….. 

1. `Je,Yesu atakaporudi anakuja kufanya nini?.

Katika swali hili ndipo tunapata Siri ya pili ambayo Ibilisi hapendi kuruhusu watu kuijua na kuiamini,kwa maana ametumia mbinu kubwa sana kuificha siri hiyo licha ya kwamba bado Mungu ameendelea kuwafunulia watu wake juu ya ukweli huo,lakini Ibilisi naye ameinua mambo kadhaa ili kuuficha na kuupotosha ukweli uliofunuliwa kwetu na Yesu Kristo.Katika kuificha siri hii ambayo ina nguvu kubwa ya kurudi kwa Yesu,Ibilisi ametumuia mambo makuu matatu…

1. `Fundisho la uongo juu ya kurudi kwa Yesu.
1. `Unabii wa uongo juu ya mambo yatakayotokea wakati wa kurudi kwa Yesu.
1. `Miujiza ya mambo ya mwilini kuhalalisha uovu wa Rohoni.

Fundisho kubwa lililopo katika vichwa vya watu kwa nyakati za sasa ni kwamba Yesu atakaporudi,anakuja kulinyakua Kanisa lake,na kwamba wale watakaokuwa wamefaulu watanyakuliwa na kumlaki mawinguni.Fundisho hili ni kweli na kwamba limeandikwa lakini tukilishika kama linavyofundishwa basi Ufunuo wa Yohana aliopewa na Yesu Kristo utakuwa wa uongo kwa maana katika kitabu hiki tunapewa kila njia na namna ambayo itafanyika kabla ya Yesu kuimaliza kazi yake yote ya kuukomboa ulimwengu.

Maswali tupaswayo kujiuliza ili tuweze kugundua hila aliyoipenyeza Ibilisi katika fundisho ni kama yafuatayo………

1. `Kama Yesu atarudi kunyakua wateule wake na watamlaki mawinguni,Je,ni kwa nini  imeandikwa kwamba Yesu atakaporudi,atatawala Pamoja na watakatifu kwa miaka elfu moja?

1. `Je,mbona tena imeandikwa kwamba shetani atafungwa kwa miaka elfu moja kisha atafunguliwa tena ilia pate kuwadanganya wanadamu?

1. `Je,mbona imeandikwa kwamba upo ufufuo kwa kwanza na wa pili?,na pia ipo mauti ya kwanza na mauti ya pili?.

1. `Je,mbona imeandikwa kwamba baada ya Yesu kutawala miaka elfu moja Pamoja na watakatifu,wakati huo shetani atakuwa amefungwa wala asiweze kumdanganya hata mtu mmoja,ndipo,hao waliofufuliwa katika ufufuo wa kwanza hawatapatwa na ile mauti ya pili?

1. `Je, kama angekuwa anarudi kulinyakua kanisa kwanini afanye vita na wapotoshaji kwa maana imeandikwa kwamba Yesu atafanya vita na kuwashinda yule nabii wa uongo Pamoja na yule mnyama na kuwatupa motoni?na wale waliosalia wakauwawa kwa upanga utokao katika kinywa chake?

1. `Imeandikwa kwamba vipo viti vya enzi wakaketi juu yake hao wasiomsujudia Yule mnyama,wala kupigwa chapa yake.kama Yesu atarudi kulinyakua kanisa je,vile viti vya enzi wanakalia akina nani?kwa ajili ya kutawala nini? Je,kuna tofauti gani kati ya kiti cha enzi cha Mung una viti vya enzi vilivyoandikwa katika kitabu cha ufunuo?.

1. `Mbingu mpya na nchi mpya vilikuja mwisho baada ya Yesu kutawala Pamoja na watakatifu kwa miaka elfu moja,kama ni kweli Yesu atarudi kulinyakua kanisha anakwenda kutala nao katika dunia ipi?
maana imeandikwa kwamba Yesu atatawala Pamoja na watakatifu katika dunia hii hii tuliyopo.

Ndugu ukijiuliza maswali hayo utagundu upo mtego mmbaya sana na ulioratibiwa vyema sana kupitia mafundisho ya kiimani,n ani mafundisho yaliyopenyezwa na Ibilisi kupitia watu aliowapa nguvu na kuaminiwa kusudi walete maarifa yasiyo ya kweli kupitia Imani (Dini).Jambo hilo sio la bahati mbaya bali linapewa uwezo na Roho yule wa uovu na linaingia na kukaa mioyoni mwa watu ili kwamba wasipate shabaha ya kuyaishi Maisha yapasayo ili wapate kushinda wakati wa ile dhiki kuu.

Nguvu ya Ukristo haipo kwa sababu ya kupewa msamaha na kuzaliwa mara ya pili kwa Neema ya Yesu Kristo pekee,bali nguvu ipo katika kumaliza kwa kuilinda Imani ya Ushahidi wa Yesu Kristo.Katika kuyakabili na kuyavumilia mateso tunayoyapata na watakayoyapata wale watakaobeba dhamana ya Ushahidi baada ya sisi,ni lazima Imani yetu iwe imtokana na kweli ya Yesu Kristo,lakini Zaidi ni lazima tuwe wa uzao wa Mungu baba Kupitia neema ya Yesu mwenyewe.

Tukijidanganya kwa maneno matamu ya kutiana moyo na kufarijiana ya kwamba Mungu ameturidhia bila ile kweli ya Yesu Kristo,basi tujue tunajiangamuza wenyewe kwa upumbavu wetu na kwa nguvu ya yule muovu Ibilisi.Kwa maana ni kweli kwamba pasipo kuwa na uzao halisi hakuna awezae kuwa shshidi wa Imani ya Yesu Kristo.na hata kama mtu ataigiza kwamba amepata uzao bila kuwa uzao halisi basi amepata hasara yake mwenyewe.

Fundisho juu ya kurudi kwa Yesu,linabeba siri kuu mbili KUSHINDA NA KUSHINDWA,nani anashinda nan ani anashindwa ni siri ambayo haikuwahi kufunuliwa hapo awali wakati wa mababu zetu.Lakini hata baada ya kufunuliwa kwake bado Ibilisi alijua nguvu ya Ufunuo huo ndipo akaanza na mikakati ya kupotosha fundisho la Ufunuo wa Yohana.

Wengi wakiwa hawapendi kukisoma kitabu chenyewe,wengine wakiwa hawawezi khata kusikiliza mafundisho ya kitafu chenyewe,na kundi lenye hatari Zaidi ni lile linalosoma na kusikiliza pasipo kuongozwa na Roho Takatifu wa Mungu,na kujikuta wakitoa tafsiri za matukio wanayoyaoanisha na Unabii wa kitabu cha Ufunuo.

***(Siri ya kushindwa kwa Ibilisi na Kushinda kwa Yesu Kristo kulifunuliwa ili tuwe katika tumaini linaloishi,tusiwe waoga wala waenendao kwa mashaka bali wenye kweli na hakika ya mambo yajayo,hata tujapokufa tufe katika tumaini la kweli la USHINDI WA YESU KRISTO.Maarifa ya kuujua mwisho wa jambo yatakupa sababu ya kuishi vyema.)***

# NAFASI YA KANISA KATIKA HISTORIA.

Katika muendelezo wa kukitafakari kitabu cha Ufunuo wa Yohana,tunakutana na jambo kuu la tatu baada ya mateso,unabii wa kurudi kwa Yesu,ambalo ni nafasi ya kanisa katika historia ya ukombozi wa mwanadamu.Katika kutafakari na kutolea ufafanuzi yaliyoandikwa katika kitabu cha Ufunuo tunaona dhari kuna mchango mkubwa sana wa Kanisa kama ushirika katika safari ya wokovu hapa duniani.

Ushirika katika Roho ni jambo la Rohoni lakini ushirika katika tabia za Roho wa Mungu ni jambo la mwilini.Wengi tunachanganya kati ya ushirika wa Roho na ushirika wa tabia za Roho.Kwa sababu tunapewa na kupokea mafundisho bila kuyatafakari kwa kina.Kwahiyo tumejikuta mara nyingi tukienenda isivyopasa kwa sababu ya kutokupata tafsiri sahihi ya Roho.

## Ushirika wa Roho; 

Ni hali ya Mtu kuungamanishwa na Mungu kwa njia ya kuzaliwa mara ya pili,yaani tunashiriki Roho ya Kiungu,tunafanana na Mungu katika Roho,Tunashiriki siri za Mungu,Tunafanya kwa niaba ya Mungu,Tunanena kwa niaba ya Mungu na Tunaonya/Kukemea kwa niaba ya Mungu kwa maana tumekuwa Roho moja naye,kwa yeye kutufanya uzao wake kupitia Yesu Kristo.

## Ushirika wa tabia za Roho; 

Ni hali ya sisi wanadamu tuliomwamini na kuzaliwa mara ya pili kwa Imani moja ya Yesu Kristo kuja Pamoja na kutengeneza kundi moja kwa ajili ya kupeana na Faraja katika Mateso ya Ushahidi wa Yesu Kristo.Kutegemezana katika vipawa vya Roho Takatifu wa Mungu.

- Mtume kwa ajili ya kuasisi kazi ya Yesu mioyoni mwa watu
- Nabii kwa ajuli ya kuyanena maagizo ya Mungu kwa watu 
- Mwalimu kwa ajili ya kuyatafsiri maneno ya Mung una kuwapa elimu ya siri za ufalme wa Mungu
- Mchungaji kwa ajii ya kuwaunganisha ndugu katika familia ya upendo wa Yesu Kristo.
- Mwinjilisti kwa ajili ya ushuhuda wa kazi ya Yesu Kristo na Nguvu ya Wokovu kwa neema ya Yesu.

Hizo nilizoziorodhesha hapo juu ni karama za Roho Takatifu wa Mungu ambaye anatengeneza tabia miongoni mwa wat una kuzitumia katika kuujenga umoja wa Roho.Ushirika huo unakuwa na Imani moja,Ubatizo mmoja,Kundi moja,Roho mmoja na Mungu mmoja.Na Mungu huyaponya mataifa kwa ushirika huo,na wala hakuna yeyote afanyaye kwa kutaka kwake bali kwa muongozo wa Roho Mtakatifu.

Hivyo kanisa ninalolizungumzia hap ani lile la Ushirika wa tabia za Roro,ambalo tunaona katika Kitabu cha Ufunuo linatokea katika nafasi ya tatu kwa maana ili kukamilisha mpango wa Mungu,hakuna budi pakawa na kundi ambalo watatiana moyo,Watakumbushana na kupeana maagizo ikiwemo kula amini kati yao,ya kuenenda katika njia ya Kweli ya Yesu Kristo hata kama mateso na dhiki itakuwa ya kuwafanya wafe.

Kundi hili ni Muhimu kwa maana katika nyakati za dhiki kuu,hapatakuwepo mtu awezaye kuyapita kirahisi magumu yenye kiasi cha kutoa Roho yake bila kuhitaji Faraja kutoka kwa mwenzake ambaye wapo katika safari ya Tumaini linaloishi la Yesu Kristo.Hivyo kanisa lipo katika nafasi kubwa ya kuwatunza na kuendelea kutetea mapenzi ya Mungu dhidi ya wale waliosimamishwa na Ibilisi ili wawataabishe watu hadi washiyashike yale yampendezayo Mungu.

***(Kanisa kama ushrika linabeba Tumaini la wateule katika nyakati za Dhiki kuu na mateso ya mashahidi wa Imani ya Yesu Kristo,ndilo ghala la kukusanyia watakatifu/wateule wa Mungu.)***

# DHANA ILIYOENEA JUU YA MAKANISA SABA YA ASIA.

Kwasababu tumekwishakuona katika jambo la tatu la ujumbe kwa Kanisa lililokuwa Asia wakati wa Mtume Yohana,aliyeandika kitabu cha Ufunuo,ni vyema sasa tukaanza  kutizama namna ambavyo watu wengi wamekuwa wakigawanyika katika fundisho la Habari ya Makanisa saba yaliyoandikwa katika kitabu cha Ufunuo,ambapo pia tutaona hila aliyoipenyeza Ibilisi kupitia mafundisho hayo ili tu watu wasiweze kuzitambua nyakati na ishara zilizofunuliwa kwetu.

##  Kuamini kwamba ni vipindi saba vya kanisa kabla ya kurudi kwa Yesu.

Fundisho la kwanza na lililoenea sana ni kwamba Habari iliyoandikwa kuhusu makanisa saba katika Ufunuo,ni kwamba hayakukusudiwa makanisa hayo bali ilikuwa ni unabii kuonesha vipindi ambavyo kanisa litapitia hadi pale Yesu atakaporudi.Fundisho hili ni kutokana na kwamba Makanisa yote yaliyoandikwa katika kitabu hicho yaliandikwa katika hali tofauti tofauti na jinsi Yesu alivyoyaonya na kuyakumbusha wajibu na kusudi lao,hivyo wengi huyahusisha makanisa yale kama ni vipindi saba vya kanisa ambavyo lazima kanisa lipitie kabla ya kurudi kwa Yesu.

*Jambo/fundisho hili mimi binafsi sikubaliani nalo kwa maana linakosa uhalisia wa matendo.*

##  Kuamini kwamba ni hatua saba mtu anazopitia baada ya kuokolewa kutoka dhambini.

Fundisho la pili ni kwamba yale yaliyoandikwa kuhusu makanisa saba katika ufunuo ni hali/vipindi tofauti tofauti katika Roho ambavyo mtu anapitia baada ya kumuamini Yesu Kristo na kuanza ukurasa mpya wa Maisha ya uchamungu.Na kwamba hatua hizo mtu atazipitia hadi pale atakapokuwa anakufa katika mwili,kwamba yale ni mapito ya Kiroho na hayana uhalisia na mwili/Maisha halisi.

*Jambo/fundisho hili pia linakosa kabisa uhalali kwa maana sote tunajua na tumepitia taaluma ambazo zinaonesha katika historia za teolojia Pamoja na historia za ulimwengu kwamba maeneo na makanisa hayo yapo na kwamba kumbukumbu zake hazijapotea hadi leo (Historic sites).*

## Kuamini kwamba Unabii juu ya makanisa yale ulikwisha kutimia wakati wa Milenium.

Lipo fundisho linaloamini kwamba Unabii wa makanisa yale haukua ukiyalenga makanisa yale bali ni nyakati za kanisa zijazo ila wanaamini kwamba ulikwisha kutimia wakati wa millennium.fundisho hili linahusisha kumbukumbu mbalimbali zikiwemo Kupanda na kuanguka kwa ufalme wa Kirumi,na kupungua kwa nguvu ya ushawishi wa warumi katika ulimwengu.Watu katika jamii za magharibi na mashariki ya mbali walijiandaa kwa hakika zote kwamba Yesu angerudi katika kipindi cha Milenium ya kwanza,Lakini wengine wakaenda mbali Zaidi na kuukubali na kupitisha Ukristo kuwa ndio dini za nchi zao(Christian states) kama yalivyo mataifa mengine **(Islamic states)**.

Lakini baada ya hayo waliyoyatarajia kutokutimia basi hata nguvu ya fundisho lililokuwepo ilipungua na pakatokea fundisho jingine ambalo ndilo lisemalo kwamba ni vipindi mtu anavyovipitia katika Roho baada ya kumuamini Yesu Kristo,na wengine kusema ni vipindi vya kanisa hadi pale Yesu atakaporudi.

***(Fundisho hili pia linakosa uhalali kwa maana kama lingekua kweli basi leo tungekuwa kati hatua nyingine kabisa ya nguvu ya Mpinga Kristo.na kwamba tungeona tabia moja tu ya kanisa kati ya zile yabia saba zilizoandikwa katika kitabu,ila kwa kuwa zipo tabia nyingi na tofauti basi tunaridhika kwamba fundisho hili pia linakosa sifa ya kuaminiwa.)***

# KUTIMIA KWA UNABII KATIKA ULIMWENGU.

Tazama patatokea ufalme/utawala wenye nguvu katika dunia,nao huo utawala utaleta amani katika dunia,kwa maana mataifa yataridhiana na kuweka agano la kukaa Pamoja wakishirikiana na kufanya maamuzi ya Pamoja.Kutakuwa na jumuia moja yenye nguvu katika dunia yote nao watapatana katika mambo mengi,na kutakuwa na nguvu ya taasisi kuliko nguvu ya mtu mmoja mmoja,kutakuwa na nguvu ya Umoja wa Mataifa.

Umoja huo wa mataifa utapitisha sheria na taratibu ambazo zitapaswa kufuatwa na mataifa yote,**UNIVERSAL DECLARATION ORDER** ,na amri hiyo itatekelezwa duniani pote,Amri hiyo itabeba ahadi na nafuu nyingi kwa watu wote,kwani itakuwa na mazuio mbalimbali ambayo yatawapendeza watu machoni pao,kwa muda wa miaka mitatu amri hiyo italeta nafuu na masuluhisho ya matatizo ya watu,na watu wote watatukuza na kuupenda utawala huo wa Umoja wa Mataifa na kuazimia kuyafuata yote yatakayoagizwa na Umoja Huo.tetesi zake zinahusishwa na **(NEW WORLD ORDER).**

Katika nyakati hizo hapatakuwa na nguvu kwa kuwa peke yako bali kwa kuwa katika ushirika/umoja Fulani,hivyo hata katika Dini zilizopo nyingi nyakati za sasa hazitakuwa na ushawishi kwa kuendelea kuwa zenyewe bali hapatakuwa na budi kuwa katika umoja wa Imani,hivyo vitakuwepo vigezo vya Imani kukubaliana ili kufanya ushirika.

1. `Imani ya kuwa Mungu ni Mmoja
1. `Imani ya kuwaamini Manabii waliotangulia
1. `Imani ya kuamini Mungu asiyeonekana
1. `Imani ya Yesu kurudi tena kabla ya kiama

Vigezo hivyo vitafanya watu waungane na kutengeneza Jumuia moja ya Kiimani ambao utakuwa Mwamvuli wa Imani zote za dini.Na Jumuia hiyo ndiyo itakayokuwa na nguvu  ya maamuzi juu ya masuala yote yahusuyo Imani yao.**(THE WORLD RELIGION ASSOCIATION)**.Hili ndilo litakalokuwa shirika lenye nguvu na litakalofanya kazi kwa ukaribu mkubwa sana na lile shirikisho la **UNIVRSAL DECLARATION ORDER**,Mashirika hayo yatakuwa na maamuzi juu ya watu na Maisha yao,ndipo yatakapofanya maamuzi juu ya watu na mataifa kwa kipindi cha kwanza cha miaka mitatu kwa wema mkubwa na fadhili nyingi,nao watu wataufurahia umoja na ushirika huo na kuupa kibali na kuuongezea mamlaka juu ya mambo yanayowahusu watu na mataifa.

Hao wenye nguvu wawili ndio wale wenye mamlaka juu ya wat una mataifa,mmoja kwa upande wa mamlaka ya Serikali **(Mnyama)** na mwingine nguvu ya Imani ya  dini **(Nabii wa Uongo)**,huyo mwenye nguvu ya Imani atakuwa akiwakikishia wafuasi wa Imani mbalimbali kutii mamlaka inayotawala kwa maana ataipa wakfu ya kwamba imekubaliwa na MUNGU.Kisha mamlaka hiyo ya serikali itatawala kwa kutenda mambo mema kwa watu kwa miaka mitatu na nusu,kisha ikishapata nguvu kubwa ndipo itapitisha sheria zenye makufuru mbele za Mungu.Lakini wakati huo wengi wataunga mkono yote yatakayowekwa kama utaratibu na Mamlaka hiyo.

Ndipo katika nyakati hizo pataibuka/kutainuka wacha Mungu wa kweli nao watapingana na yale yanayohalalishwa na yule nabii wa uongo,ila watapingwa na wengi kwa maana wengi watakuwa wafuasi wa Dini hiyo na wengi katika wenye mamlaka ya serikali watakuwa wafuasi wa dini hiyo,hivyo watawakarahisha na kuwanyanyasa wale wa kundi dogo wanaopingana na maneno ya yule mkuu wao wa Imani,zitatungwa sheria za kuwakwaza,na kuwatia hatiani kwa yale watakayokuwa wakiyahubiri kinyume na ile dini kuu itakayokuwa na huyo nabii wa uongo.

Patakuwa na dhiki kuu wakati huo kwani hata kukusanyika ili kuabudu itakuwa ni jinai kwa wale walio kinyume na yule nabii wa uongo,wateule watashitakiwa na kufungwa magerezani,watafukuzwa katika makutano yao,watauwawa kwa hili na wengine kutengwa na jamii zao kwa ajili ya kuisimamia kweli ya Yesu Kristo.Nabii yule wa uongo atawaambia hao wafuasi wanaomfuata kumwamini na kumtii yule kiongozi wa serikali kuu,na kumfuata yeye.Nao wayamsikiliza kwa maana ni wakati ulioamuliwa na kupangwa kwa ajili ya hayo.

Serikali hiyo itatengeneza mfumo mmoja wa kuwaratibu wanadamu kwa ajili ya huduma za kijamii,na kuwahakikishia usalama wao kupitia mfumo huo.Mfumo huo utaweka alama ya utambulisho kwa kila mwanadamu,tangu mdogo hadi mkubwa,kwa ajili ya kuratibu mambo yote katika jamii za wanadamu,alama hiyo ndiyo alama ile ambayo mtu hatanunua wala kuuza asipokuwa na alama/chapa hiyo katika paji la uso au mkononi mwake.

Zitakuwa ni nyakati za taabu na dhiki kwa wale watakaopinga na kukataa chapa hiyo kwani hawatakuwa na fungu kati ya hizo huduma za kijamii,Leo hii tunaweza kuona ilivyo taabu kwa mtu kupata mawasiliano pasipokuwa na kadi iliyosajiliwa kwa alama za vidole,basi zitakuja nyakati haitawezekana mtu kupata huduma ya kijamii bila kuwa na chapa hiyo iliyosajiliwa taarifa zake.badala ya wanadamu kutumia kadi basi watawekewa mionzi **(Cheep)** ndani ya miili yao kwa ajili ya kuweka kumbukumbu zaozote tangu kuzaliwa hata kufa kwao.

Hiyo cheep ndiyo chapa yenyewe na itatumika kuwatambua wat una kuwapa huduma,ikiwa ni matibabu,manunuzi ya mahitaji,kuhifadhi fedha na pia kwa ajili ya ulinzi binafsi pale unapokosa usalama ili uweze kupewa msaada basi utakuwa huna budi kutumia utambulisho wako huo kuwashiliana na mamlaka husika.Wanadamu wataungana na kusikilizana kwa mambo mengi,licha ya tofauti zao za rangi na mipaka ya jiografia.basi wale waliokubali kuyashika maneno ya nabii yule wa uongo na kuyafuata watakuwa wamoja,na wale wanaoyapinga na kutokuyafuata pia wao nao wataungana ili kuwa na nguvu ya Pamoja. **TOGETHER AND WIN OR ALONE AND PERISH.**

Ndipo kundi dogo litakapoandwamwa kwa sababu ya misimamo yake ya kweli,nao watateseka kwa kukosa huduma za kijamii,watawekwa gerezani,watashitakiwa kwa uongo,watauwawa kwa siri na wengine hadharani hata pale idadi ya Bwana Mungu itakapotimia ya hao watakaokuwa tayari kuilinda Imani hadi mwiso/hata kufa ikibidi.Ndipo yale yalioandikwa kwamba yatawapata hananabudi kuwapata na kwamba lazima maneno ya unabii huu yatimie.

Ndipo Yesu Kristo atakapoweka nguvu ya ushindi wake kwa watu wake na yeye akiwa kati yao,atakapoiondoa ule Ufalme/serikali ya Mpinga Kristo **(Mnyama)** kumtoa katika madaraka yake kwa kushindwa na wale wenye kweli ya Kristo,na pia atapoiondoa ile dini kuu (nabii wa uongo),nao wote wawili wataanguka na kukosa wafuasi kwa maana watu watakuwa wameamini ile kweli ya Yesu Kristo na kuifuata,hivyo nguvu yao itaondoka katika dunia na hapo pataanza kusimama tena falme mbalimbali katika ulimwengu kila moja kwa misingi ya haki ya Yesu Kristo.

***(Hiyo ndiyo miaka elfu ambayo Yesu atatwala katika falme zote duniani na Ibilisi atakuwa amefungwa kuzimu,hapatakuwa na udanganyifu katika dunia kwa hiyo miaka elfu.Hiyo itakuwa ni ufufuo wa kwanza kwa wale waliokuwa mashahidi wa ile Imani ya kweli ya Yesu Kristo.)***

# IDADI YA JINA LA NAMBA YA MNYAMA.

Kati ya mada zinazojadiliwa kwa ufafanuzi tofauti ni mada ya namba ya jina la yule mnyama ambaye jumla yake ni 666.Na unabii unasema ni hesabu ya kibinadamu.Binafsi nimepata kusikia mafundisho mengi juu ya hesabu hiyo,lakini kama nilivyopata tafsiri ya Mnyama na Nabii kama Mungu alivyonijaalia basi katika kusoma kwangu,niliona siri nyingine iliyojificha ndani ya maandiko yenyewe,ambayo sio inayotokana na mawazo binafsi bali ndani ya maandiko ya unabii wa kitabu hicho.
Ili kupata mchanganuo mzuri nitaweka kwa Muhtasari yale maandiko yanayohusisha siri hiyo kwa mtiririko wake kama yalivyoandikwa.

## 1.MUHURI SABA. Ufunuo wa Yohana 6: 1 -- 12

**Muhuri ya kwanza** 

ni kipindi amba Yesu alitufia msalabani akashinda ilia pate kushinda katika sisi tulioliamini jina lake na kuishika ile kweli aliyotufundisha,kukawa na amani na tumaini katika dunia kwa maana Yesu alituletea ushindi kwa kupewa msamaha wa dhambi kwa msaada wa Roho wake Takatifu.

**Muhuri ya pili**

Ni nyakati za vita katika dunia watu watachukiana na kuuwana wao kwa wao wengine wakitetea haki zao na wengine wakidhulumu (Machafuko katika dunia).

**Muhuri ya tatu**

Ni nyakati za njaa kuu katika dunia,mazao hayataona kama ilivyo desturi wala matunda kwa majira yake kwa maana ni kipindi kilichoamuriwa kuwako.

**Muhuri ya nne**

Ni nyakati za magonjwa/maradhi ya mlipuko  na vita na njaa na mauaji ya Wanyama porin a wenye hatari katika dunia.

**Muhuri ya tano**

Ni  nyakati ambazo wale waliokuwa mashahidi wa ile Imani ya kweli kwa Yesu Kristo na walioenenda katika njia za haki na hukumu za Mungu walipouwawa kwa ajili ya jina la Mungu.

**Muhuri ya sita**

Ni nyakati za utisho wa Mungu kwa wanadamu na Dunia yote,kwa maana vitu vyote vitatiishwa na kuharibiwa kwa namna ambayo sio ya kibinadamu,matetemeko,giza,na utisho wa kila aina ambao wanadamu hawajawahi kuuona,siku ya hasira ya Bwana Mungu.Na ndipo wakati huo wale waliokuwa wakidumu katika kweli ya Yesu Kristo watakapowekwa muhuri ya Mungu katika mapaji ya nyuso zao.

Katika fungu hili la kwanza tunaona nyakati sita zinazotendeka duniani,kwa maana yote hayo yaliyofungwa katika mihiri hizo sit ani mambo ya duniani. Hiyo ndiyo ile sita ya kwanza **(6).**

**Muhuri ya saba**

Ilikuwa inafunua Habari za baragumu yaani nyakati zingine sita zipaswazo kuwapo,hivyo muhuri hiyo ilikuwa  ikionesha uratibu wa nyakati zingine katika nchi.Muhuri hii inatuonesha mambo yaliyokuwa yakiendelea mbinguni.

## BARAGUMU SABA. Ufunuo wa Yohana 8: 7 – 13 na  9 : 1 --13

**Baragumu ya kwanza**

Ni pigo la ardhi na mimea kwa  mvua za mawe na damu ambazo zitaharibu uoto wa asili wa nchi na kuharibu ardhi.

**Baragumu ya pili**

Ni pigo la bahari ambapo bahari itaharibiwa maji yake na viumbe wakaao ndani yake watapotea kwa sababu ya athari hizo.

**Baragumu ya tatu**

Ni pigo la maji ya mito na chemchem hivyo maji yakatiwa uharibifu na hivyo yakageuka kuwa sum una kuwadhuru wanadamu.

**Baragumu ya nne**

Ni pigo la anga kwa maana nyota mwezi na jua vitaharibiwa uasilia wake na kutiwa giza theluthi yake hata havutaweza kuangaza kama ilivyo kawaida yake.

**Baragumu ya tano**

Ni pigo la maumivu/mateso kwa wanadamu kwa miezi mitano kwa kutumia nzige wenye mfano wa nguvu za nge kutoka shimoni (Kuzimu) kwa wale ambao hawakuwekwa chapa ya Mungu katika mapaji ya nyuso zao kama tulivyoona katika Muhuri ya sita.

**Baragumu ya sita**

Ni pigo la mauaji kwa wanadamu kwa moshi na moto na kiberiti kutoka kwa Mungu kupitia wale Malaika walioandaliwa kwa ajili ya siku na mwezi na saa na mwaka.Lakini hata baada ya hayo watu hawakutubu mbele za Mungu na kuziacha njia zao za kuabudu sanamu na wizi na uzinzi.

Hivyo tunaona tena vipindi sita ambavyo vitatolea katika nchi na namna ambavyo wanadamu hawatabadilika na kumgeukia Mungu licha ya mapigo yote ambayo yatakuwa Dhahiri.Hii ndiyo sita ya pili **(6).**

**Baragumu ya saba**

ikapigwa kwa maana iliwekwa kwa ajili ya siku hizo za mwisho kabisa kwa maana itakuwa ndio baragumu ya kuwafufua wafu wote kwa ajili ya hukumu ya mwisho.kwani imeandikwa hapatakuwa na muda tena baada ya Malaika huyo wa saba atakapopiga baragumu ya saba.

Katika baragumu hii ya saba pia tunaona inaelezea Habari/jambo litendekalo mbinguni kama ilivyokuwa Muhuri ya saba ilivyoelezea mambo yaliyokuwa yakitendeka mbinguni.

## MABAKULI SAB/VITASA SABA. Ufunuo wa Yohana 16: 1 – 16.

**Bakuli la kwanza **

Likamiminwa kwa ajili ya kudhuru watu kwa majipi kwa wale wote wenye chapa ya yule mnyama na walioisujudia sanamu yake.

**Bakuli la pili**

Likamiminwa kwa ajili ya kuyaharibu maji ya bahari na viumbe wote waishio humo wakafa kwa sababu ya madhara yake.

**Bakuli la tatu**

Likamiminwa kwa ajili ya kudhuru mito na chemchem nazo zikawa damu hata maji yake yasiwe salama kwa matumizi kwa watu hayo yalifanyika kwa ajili ya kuwalipia wale manabii na mashahidi wa Mungu waliouwawa kwa ajili ya kweli na Imani ya Mungu.

**Bakuli la nne**

Likamiminwa jua likadhuriwa na kutoa moto wanadamu wakaunguzwa kwa joto/moto wa jua lakini pia hawakumrudia Mungu bali walimtukana jina lake na wala hawakutubu.

**Bakuli la tano**

Likamiminwa juu ya Ufalme/uongozi wa hiyo serikali.ufalme wao ukatiwa giza maana yake wakakosa uelekeo/masuluhisho ya matatizo ya watu,wakapingana wao kwa wao katika ufalme huo.Wala hawakutubu.

**Bakuli la sita**

Likamiminwa na ndipo patatokea zile Roho za uongo tatu zitendazo ishara, kutoka magharibi,moja itatoka katika yule mnyama(Ule Ufalme), Moja itatoka kwa yule nabii wa uongo(katika ile Dini), na Moja itatoka kwa Ibilisi mwenyewe.Hizo ndizo nyakati nyingine (6).

**Bakuli la saba**

Likamiminwa na tazama tunaona tena likizungumzia Habari ya Mbinguni,kutoka katika Hekalu la Mungu saw ana ule Muhuriw a saba Pamoja na Baragumu ya saba.

### Muhtasari.

Ukiangalia kwa Habari ya ulimwengu tunaona nyakati zimegawanya katika mafungu makuu matatu, Kipindi cha Muhuri,Kipindi cha Baragumu na Kipindi cha Mabakuli/Vitasa.katika mafungu yote haya kwa Habari ya nchi zinazungumziwa nyakati sita kwa kila fungu moja,na tunaona katika kila fungu limezungumzia Habari ya mbinguni mara moja.

- **Mihuri sita (6)  Habari zihusuzo ulimwengu.**
- **Baragumu sita (6)  Habari zihusuzo ulimwengu.**
- **Bakuli/Vitasa sita (6)  Habari zihusuzo ulimwengu.**

**Nyakati zote 666** zitatokea katika nchi kabla ya Yesu Kristo Kurudi kwa ajili ya ukombozi wa Dunia,nasema ukombozi wa dunia kwa sababu,ukombozi wa Yesu Kristo aliokufa Msalabani ulikuwa kwa ajili ya kumkomboa mwanadamu na kumpa upatanisho na Mungu,kisha atarudi kwa ajili ya kumwondoa Ibilisi na kumfunga kuzimu ili asipate nafasi ya kuupotosha ulimwengu,na huo utakuwa ndio Ukombozi wa mwisho na kisha kitafuatia kiama.

Katika historia ya uumbali wa Mungu,tunasoma kwamba Mungu alianza kwa kuumba Mbingu na Nchi kisha akaumba na kufanya vitu vyo viijazayo nchi na baadae akamuumba Mwanadamu kwa ajili ya kukaa katika hiyo nchi.Lakini katika kuzaliwa mara ya pili katika Yesu Kristo Mungu anaanza kumtengeneza/Kumzaa kwanza Mtu mpya ndipo anamwandalia mako mapya yaani Mbingu mpya na Nchi mpya.Yesu aliwaambia wanafunzi wake anakwenda kuwaandalia Makao.Kauli hiyo ilikuja baada ya Yesu kuja na kuwapa watu ile kweli ili watakapofanywa wapya Rohoni yaani kuzaliwa mara ya Pili basi wawe na makao katika ule ufalme wa Baba yake naye ndiye Mungu wetu.

Hivyo Ufalme utakaoinuka **(Mnyama)** utaweka taratibu na sheria ambazo zitakuwa za kidunia zenye kuwapendeza wanadamu na sio Mungu,zitakazoleta utukufu kwa mwanadamu na kwa kazi ya mikono ya wanadamu,na kuweka yale yote yaliokweishakupita ambayo yalikuwa chukizo kwa Mungu kayafanya mambo matukufu na watu watapewa amri kuyaamini na kuyaabudu na pia kuyasujudia.Huo ndio ufalme wa ulimwengu ulio kinyume na ufalme wa Mungu.

*Muhuri wa saba ni habari za mbinguni na Baragumu ya saba pia ni Habari za Mbinguni, kadhalika Bakuli/Kitasa cha saba nacho pia ni Habari za mbinguni.*

***(Imetupasa kuyatambua mafumbo ya Mungu na hila za Adui ili tuweze kushindana kwa haki ya Yesu Kristo na kushinda kwa uweza wa Mungu Amen.)***

# MAUDHUI YA KITABU.

Katika kitabu cha Ufunuo wa Yohana kuna mambo makuu matatu ya kujifunza amabyo hapana budi kupata utulivu ili kuyafunua,

## Mateso ya wacha Mungu hapa duniani.

Mateso hayo yapo ya namna mbalimbali ambayo kila anayemwelekea Mungu kwa haki na kweli,atayapitia bila shaka.yatakuwa mateso ya hali ya kipato,mateso ya kutokusaidika kwa sababu ya kuenenda kwa unyofu,mateso ya kuwahusumia wengine na kutenda kwa niaba yao,mateso ya kukosa Faraja ya kujumuika na makusanyiko yasiyotenda na kunena kweli ya Yesu Kristo,lakini katika nyakati hizo za mwisho yatakuwako mateso makuu Zaidi kwa hao wachamungu kwa maana watafanyiwa hila na usaliti mkubwa kwa sababu ya Imani yao.

## Kupotoka kwa wateule.

Hali hiyo ya wachamungu wa kweli kuteseka,itawafanya watu wengine kutokumwamini mungu wa kweli na kumfuata yule aletaye nafuu ya mambo ya wanadamu pasipo wao kujua ya kwamba,hayo yapendezayo machoni ni ya muda tu na hayadumu milele.hivyo hata baadi ya wateule wataingia shaka/kupoteza tumaini juu ya Yesu Kristo kwa maana wataona ni kana kwamba Mungu amewaacha/hayupo.Ila katika kitabu hicho hicho kinatuonesha kwamba Pamoja na magumu na mateso tunayopitia bado Mungu yupo katika mamlaka yake na ameyaruhusu hayo kwa majira maalumu na kwa hesabu maalumu kabla hajayakomesha.

## Milki ya Mungu katika dunia.

Kisha tunaona baada ya yote ya mateso na Mungu atakakoyakomesha yote mabaya katika nchi,basi dunia yote itatawaliwa na Mungu kupitia mwanaye Yesu Kristo na wale wote waliokuwa na kweli yake na kuenenda katika njia yake na kuwa mashahidi hata kufa yaani watakatifu wa Mungu watatawala Pamoja naye,kwa kuwaweka kuwa wafalme na watoa hukumu juu ya mataifa,katika wakati huo wale waliojitoa miili na nafsi zao kwa ajili ya Mungu basi watastarehe na mateso hayatakuwako tena kwao.kwa maana watatawala Pamoja na Yesu.

## Uasi mkuu.

Baada ya hayo yote kupita pindi Ibilisi atakapofunguliwa tena ili awapotoshe wanadamu,basi atatengeneza kundi kubwa sana naye atapanga vita dhidi ya Yesu Kristo **(Ufalme wa Mungu)**. Kwa madai mengi ya ushawishi atawadanganya wengi,kwa maana sote tunajua utawala wa Mungu ni wakifalme yaani hakuna demokrasia ya kuchagua unachokitaka,hivyo kwakuwa watu watakuwa katika amri moja toka kwa mfalme na wakuu wake basi Ibilisi atatumia mbinu ya kuwapa watu uhuru wa kujichagulia walitakalo,akiahidi kuwapa watu uhuru wao ambao hawatalazimika kufuata amri za ufalme yaani ataleta **(DEMOCRACY)**.Watu wengi watamuunga mkono na kumfuata ili wapate kuishi kama watakavyo wao wenyewe,huo ndio ule uasi mkuu,kwa maana watajipanga kwa vita ya mapinduzi,lakini kwa kuwa utakuwa ni wakati uliokusudiwa basi Mungu atawateketeza kwa Moto wote waliomfuata na kumtupa Ibilisi Katika ziwa la moto humo alimo yule nabii wa uongo na yule kahaba.

## Hukumu ya mwisho.

Kisha baada ya hayo ndipo itakuja siku ya hukumu ya mwisho kwa watu wote,wafu na walio hai,wafu wote watafufuliwa wakuu kwa wadogo,na watakatifu wote na wenye dhambi wote kwa ajili ya hukumu.na hiyo itakuwa kama hukupata nafasi katika ule ufufuo wa kwanza basi mauti hii ya pili hutaweza kuiepuka.Ndipo wale ambao hawakuandikwa katika kitabu cha uzima watakapotupwa katika lile ziwa la moto alipo yule kahaba na nabii wa uongo na mnyama.Na huo utakuwa mwisho wav yote,naye Mungu atavifanya upya vitu vyote Mbingu,Nchi na Yerusalemu.kisha hao watu nao watakuwa wapya ili kuiingia nchi mpya.

***Bwana Mungu atusaidie sote kwa neema yake,tudumu katika kweli yake na kuwa mashahidi wa Imani yake kwa kuisema na kuitenda ile kweli ili tuwe wenye kibali machoni pake,tuishi na tudumu na kufa katika njia yake ya KWELI AMEN.***

# MJUMUISHO JUU YA MAFUNDISHO HAYO.

Kwa kujuisha,Mimi mara zote katika Makala zangu nimekuwa muumini na muhamasishaji wa mambo makuu matatu,…

- Tuisome Biblia kama ilivyoandikwa na kutafuta maana na kiini cha andiko husika.
- Kuruhusu muongozo wa Roho Takatifu wa Mungu kutuongoza katika kufasiri maandiko.
- Kuwa na Subira katika kungoja wakati wa Mungu huku tukiwa macho kuziona ishara alizotuambia tuzingoje maana lazima zitokee.

Hivyo nianze kwa kusema Biblia kama ilivyoandika kitabu cha Ufunuo wa Yohana,katika historia na pia katika maongozi ya Roho Takatifu wa Mungu,niwazi na kweli kwamba yote yaliyoandikwa hayana budi kutokea katika udhahiri wa mwilini japo yanayo tafsiri yake katika Ulimwengu wa Roho,
Lakini pia tukumbuke kwamba ulimwengu wa Roho ndio unaoutiisha ulimwengu wa mwili na maumbile,hivyo basi kama tunavyoheshimu udhahiri wa mwili basi yatupasa kuamini na kuwa na hakika kwamba ulimwengu wa Roho unatenda kazi sawasawa katika kuratibu mambo yapasayo kutokea katika mwili.

Hivyo mambo hayo yaliyoandikwa katika kitabu hicho japokuwa yanartibiwa katika Roho,lakini pia hayana budi kutokea katika mwili,kwamba ni kweli Makanisa hayo yalikuwako katika pande za Asia kama inavyonenwa katika Biblia (Uturuki ya sasa).na yote yaliyoandikwa katika onyo la Yesu kwao yalitokea n ahata leo tunavyozungumza maeneo hayo yamebaki kuwa kama kumbukumbu za kihistoria pekee.

Hivyo kwa habaria zote ni kwamba yote yalipaswa na yatapaswa kutokea ili tu maandiko ya unabii yapate kutimia.Kwa kusema hivyo ninamaanisha tuasome maandiko kwa uhalisia wake pale yanapoandika kwa Habari halisi za mwilini,na pia tuyape maana maandiko pale yanaponena habaria za Rohoni/mafumbo ya Rohoni.Sio sahihi kuwapa watu utisho wa mafumbo kwa Habari zilizo za wazi wazi,na pia sio sahihi kuwapa watu mambo ya mwilini kwa Habari za mafumbo ya Rohoni.

Tumpe Roho nafasi pale yanapohitajika kuyanena ya Rohoni lakini pia imetupasa kuwa na hekima pale yanapokuja mambo ya mwilini.Kwa maana mambo yote hayo yameandikwa na yalinenwa kwa ajili yetu sisi,ili kwamba kwa kuyasoma tupate kuijua ile iliyokuwa nia na shabaha ya kuneno/kuandikwa kwake.

Mambo yaliyoandikwa katika kitabu hiki cha Ufunuo yanatupa onyo kali sana mwishoni mwa kitabu,na onyo hilo la kinabii lilitolewa kwa kuwa Mungu alijua wapo watu watakaopotosha maono hayo kwa njia za elimu mbali mbali,na kwamba wapo watakaokuwa wakitumika na yule muovu pasipo wao kujitambua,kwa maana watapokea fundisho la uongo nao pia wataliendeleza fundisho hilo.Hivyo ilitolewa **(Ole)** kwa yeyote atakayethubutu kufanya hayo Aidha kuongeza au kupunguza maneno ya unabii wa kitabu hicho.

Ndio maana hata katika kuchapwa kwake kilikuwa kitabu cha mwisho kabisa kuridhiwa kuingia katika mjumuiko wa vitabu katika Biblia.

***(Ashukuriwe Mungu kwa maana aliruhusu tukisome na kukihifadhi karnr kwa karne hata kizazi cha leo,kwa maana hazina hiyo ingepotea basi yawezekana tusingepata kwa kina kuyajua yaliyo katika hatma ya mwanadamu. ***




















- NEEMA YA YESU YATOSHA,KWA SADAKA MOJA ALIYOITOA KWA KUFA KWAKE SISI TUMEPATA UKOMBOZI WA MILELE,NA KWA MSAADA WA ROHO WAKE MTAKATIFU SISI SOTE TUNAPEWA UWEZA WA KUSHIRIKI TABIA ZA MUNGU.

- TUMUAMINI YESU KRISTO KWAMBA ALIKUFA KWA AJILI YA DHAMBI ZETU ILI ATUPATANISHE NA MUNGU BABA.TUZITUBIE DHAMBI ZETU KWA MUNGU MAANA TULIKOSA MBELE ZAKE,TUSHUKURU KWA USHINDI WA YESU KRISTO KWA KUFUFUKA KWAKE,ILI NASI TUWE HAI KATIKA YEYE,NA TUISHI KATIKA UBATIZO MMOJA WA ROHO MTAKATIFU ANAYETUONGOZA,KUTUFUNDISHA NA KUTUKUMBUSHA YALE YOTE YAIPASAYO TOBA AMEN.

